mod backend;
mod cwd;
mod layout;
pub mod ledger;
mod manager;

pub use backend::{PendingSshAuth, SessionBackend, SshAuthPrompt, SshCmd, SshSessionParams};
pub use cwd::CwdState;
pub use layout::{
    collect_leaf_pane_ids, collect_terminal_leaf_pane_ids, ensure_leaf_kind,
    extract_leaf_from_layout, first_leaf_id, insert_pane_into_layout,
    insert_pane_into_layout_with_info, insert_subtree_into_layout, remove_pane_from_layout,
};
pub use manager::{CloseReason, SessionManager, SessionStatus, SyncClient, SyncMsg, TabInfo};

#[cfg(test)]
pub(crate) use cwd::{find_subslice, parse_title_cwd, sniff_cwd_from_title_osc, OSC_SNIFF_CAP};

use crate::vt_screen::VirtualScreen;
use std::{
    io::Write,
    path::PathBuf,
    sync::{
        atomic::{AtomicBool, AtomicU64, Ordering},
        Arc, Mutex,
    },
};
use tokio::sync::{mpsc, watch};
use tracing::info;

/// Force-flush buffered synchronized output at this limit (256KB).
/// Prevents massive single payloads that freeze the frontend UI thread.
const SYNC_BUFFER_LIMIT: usize = 256 * 1024;
/// Maximum size of a single chunk sent to clients during flush.
const FLUSH_CHUNK_SIZE: usize = 64 * 1024;

#[derive(Default)]
pub struct SyncState {
    active: bool,
    buffer: Vec<String>,
    bytes: usize,
}

pub struct PendingCommandResult {
    pub exit_code: i32,
    pub duration_ms: u64,
    pub stdout: String,
    pub method: String,
}

#[derive(Clone)]
pub enum SessionClientEvent {
    Output(String),
    Resize {
        cols: u16,
        rows: u16,
    },
    SessionExit {
        pane_id: String,
        exit_code: Option<i32>,
    },
    /// DEC mode 2026 transaction boundary. `SyncBegin` is enqueued BEFORE any
    /// subsequent Output (which is buffered while synchronized output is
    /// active); `SyncEnd` is enqueued AFTER that buffer is drained, so the
    /// on-wire order is [buffered Output chunks] -> `SyncEnd` -> [post-sync live
    /// Output]. Frontend uses these to divert Output into a transaction buffer
    /// and write it to xterm as a single batch, eliminating per-chunk
    /// intermediate rAF repaints during a synchronized redraw.
    SyncBegin,
    SyncEnd,
    /// Snapshot replay transaction boundary (fit-then-snapshot handshake).
    /// `ReplayBegin` precedes scrollback+snapshot chunks generated by the
    /// server in `atomic_resize_and_snapshot`; `ReplayEnd` follows them. Same
    /// transaction-buffer mechanism as SyncBegin/End on the frontend.
    ReplayBegin {
        cols: u16,
        rows: u16,
    },
    ReplayEnd,
}

pub struct ClientEndpoint {
    pub id: u64,
    pub tx: mpsc::Sender<SessionClientEvent>,
    /// True between `add_client` (or `emit_join_sync`) and the moment the server
    /// finishes enqueuing ReplayBegin+chunks+ReplayEnd to this client. While
    /// true, `broadcast()` and `flush_sync_buffer()` drop Output chunks for this
    /// client (their effect is captured by the upcoming snapshot, so sending
    /// them live would double-paint). Control events (SyncBegin/SyncEnd,
    /// ReplayBegin/ReplayEnd) bypass this flag and always reach the client.
    pub snapshot_pending: std::sync::atomic::AtomicBool,
}

pub struct Session {
    /// 传输后端（本地 PTY 或 SSH）
    pub backend: tokio::sync::Mutex<SessionBackend>,
    /// SSH 会话参数（分屏时复用），None 表示本地会话
    pub ssh_params: Option<SshSessionParams>,
    pub screen: Mutex<VirtualScreen>,
    pub clients: Mutex<Vec<ClientEndpoint>>,
    pub next_client_id: AtomicU64,
    pub tauri_client_id: Mutex<Option<u64>>,
    pub input_tx: Mutex<Option<mpsc::UnboundedSender<String>>>,
    pub status: Mutex<SessionStatus>,
    /// Conservative lock-free mirror used only by lifecycle-locked reap claims.
    pub(crate) is_connected: AtomicBool,
    pub size: Mutex<(u16, u16)>,
    pub exited: Mutex<bool>,
    #[allow(dead_code)]
    pub shell_type: String,
    #[allow(clippy::type_complexity)]
    pub tauri_on_exit: Mutex<Option<Arc<dyn Fn(String, Option<i32>) + Send + Sync>>>,
    pub cwd_state: Mutex<CwdState>,
    /// DEC mode 2026 state. Always acquire this before `clients` when both are needed.
    pub sync: Mutex<SyncState>,
    #[cfg(test)]
    pub(crate) sync_disable_hook: Mutex<Option<Box<dyn FnOnce() + Send>>>,
    /// Sender for debounced resize requests (None = no pending resize)
    pub(crate) resize_tx: watch::Sender<Option<(u64, u16, u16)>>,
    /// Channel to send commands (input/resize/close) to the SSH reader task.
    /// None for local sessions.
    pub ssh_cmd_tx: Mutex<Option<mpsc::UnboundedSender<SshCmd>>>,
    /// SSH client handle for opening new channels (SFTP, exec).
    /// Type-erased to avoid circular deps. Actual type: `russh::client::Handle<ssh::SshClientHandler>`
    /// Uses `tokio::sync::Mutex` so the guard can be held across `.await` points.
    pub ssh_handle: tokio::sync::Mutex<Option<Box<dyn std::any::Any + Send + Sync>>>,
    /// Cached SFTP session for workspace operations. Created lazily.
    /// Actual type: `Arc<russh_sftp::client::SftpSession>`
    pub sftp_session: Mutex<Option<Box<dyn std::any::Any + Send + Sync>>>,
    /// Remote home directory for SSH sessions. Used for `~` expansion in
    /// CWD sniffing and workspace path resolution.
    /// `None` for local sessions.
    pub remote_home: Mutex<Option<PathBuf>>,
    /// Current PTY user for SSH sessions. Detects user switches (e.g. `su root`).
    /// When the PTY user differs from the SSH auth user, SFTP operations may
    /// fail due to permission issues, and SSH exec fallback with sudo is needed.
    /// `None` means not yet detected (lazy initialization on first workspace op).
    pub remote_user: Mutex<Option<String>>,
    /// Raw PTY output channel: reader sends raw bytes here for xterm.js rendering.
    /// Unbounded so the PTY reader never blocks on send.
    pub output_tx: mpsc::UnboundedSender<Vec<u8>>,
    /// Receiver side, taken once by the broadcast task.
    pub output_rx: Mutex<Option<mpsc::UnboundedReceiver<Vec<u8>>>>,
    /// Command results extracted during `feed()`, consumed by the broadcast task.
    pub pending_results: Mutex<Vec<PendingCommandResult>>,
}

impl Session {
    /// Publish status without ever co-holding the manager lifecycle lock.
    /// Connected is mirrored before the status value becomes visible; Detached
    /// clears the mirror only after the status value is committed.
    pub fn set_status(&self, status: SessionStatus) {
        let mut current = self.status.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        match status {
            SessionStatus::Connected => {
                self.is_connected.store(true, Ordering::Release);
                *current = SessionStatus::Connected;
            }
            SessionStatus::Detached { since } => {
                *current = SessionStatus::Detached { since };
                self.is_connected.store(false, Ordering::Release);
            }
        }
    }

    #[must_use]
    pub fn is_connected(&self) -> bool {
        self.is_connected.load(Ordering::Acquire)
    }

    /// Revert a failed attach publication after lifecycle membership validation.
    pub fn mark_failed_attach(&self) {
        self.set_status(SessionStatus::Detached { since: std::time::Instant::now() });
        self.mark_exited();
    }

    /// Explicitly kill the child process. Safe to call multiple times (idempotent).
    /// After this, the PTY reader task's `reader.read()` will return Err/Ok(0),
    /// causing it to exit and drop its `Arc<Session>`, which triggers `Drop`.
    pub fn kill_child(&self) {
        self.kill_backend_sync();
    }

    /// Kill the backend and confirm that it terminated without waiting indefinitely.
    ///
    /// Returns `false` when the backend lock is held or termination cannot be
    /// confirmed within the bounded polling window.
    pub fn kill_child_and_confirm(&self) -> bool {
        let Ok(mut backend) = self.backend.try_lock() else {
            return false;
        };

        let confirmed = match &mut *backend {
            SessionBackend::Local { child, .. } => {
                let pid = child.process_id();
                #[cfg(unix)]
                if let Some(pid) = pid {
                    #[allow(clippy::cast_possible_wrap)]
                    let process_group = pid as i32;
                    unsafe {
                        libc::killpg(process_group, libc::SIGTERM);
                    }
                    std::thread::sleep(std::time::Duration::from_millis(50));
                    unsafe {
                        libc::killpg(process_group, libc::SIGKILL);
                    }
                }
                let _ = child.kill();

                let deadline = std::time::Instant::now() + std::time::Duration::from_millis(250);
                loop {
                    match child.try_wait() {
                        Ok(Some(_)) => break true,
                        Ok(None) if std::time::Instant::now() < deadline => {
                            std::thread::sleep(std::time::Duration::from_millis(10));
                        }
                        Ok(None) | Err(_) => break false,
                    }
                }
            }
            SessionBackend::Ssh => self
                .ssh_cmd_tx
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
                .as_ref()
                .is_some_and(|tx| tx.send(SshCmd::Close).is_ok()),
            SessionBackend::Exited => true,
        };

        if confirmed {
            *backend = SessionBackend::Exited;
        }
        confirmed
    }

    /// Confirm a naturally-ended backend before its crash-recovery entry is removed.
    /// Uncertainty is deliberately reported as false so boot recovery retains it.
    pub fn natural_exit_confirmed(&self, pane_id: &str) -> bool {
        let Ok(mut backend) = self.backend.try_lock() else {
            return false;
        };
        match &mut *backend {
            SessionBackend::Local { child, .. } => match child.try_wait() {
                Ok(Some(_)) => ledger::termination_confirmed(pane_id),
                Ok(None) | Err(_) => false,
            },
            SessionBackend::Ssh => ledger::termination_confirmed(pane_id),
            SessionBackend::Exited => ledger::termination_confirmed(pane_id),
        }
    }

    /// 同步清理后端（用于 `kill_child` 和 Drop）
    fn kill_backend_sync(&self) {
        let Ok(mut backend) = self.backend.try_lock() else {
            // 锁被持有（SSH async 操作中），跳过同步清理
            // SSH reader task 会在连接关闭时自行清理
            return;
        };
        match &mut *backend {
            SessionBackend::Local { child, .. } => {
                let pid = child.process_id();
                #[cfg(unix)]
                if let Some(pid) = pid {
                    #[allow(clippy::cast_possible_wrap)]
                    let process_group = pid as i32;
                    unsafe {
                        libc::killpg(process_group, libc::SIGTERM);
                    }
                    std::thread::sleep(std::time::Duration::from_millis(50));
                    unsafe {
                        libc::killpg(process_group, libc::SIGKILL);
                    }
                }
                let _ = child.kill();
                let _ = child.wait();
                self.mark_exited();
                info!("Session child killed: pid={:?}", pid);
            }
            SessionBackend::Ssh => {
                // SSH channel is owned by the reader task; signal it to close
                if let Some(tx) = self
                    .ssh_cmd_tx
                    .lock()
                    .unwrap_or_else(std::sync::PoisonError::into_inner)
                    .as_ref()
                {
                    let _ = tx.send(SshCmd::Close);
                }
                self.mark_exited();
                info!("SSH session marked as exited");
            }
            SessionBackend::Exited => {}
        }
    }

    /// 异步清理 SSH channel
    pub fn kill_backend_async(&self) {
        if let Some(tx) =
            self.ssh_cmd_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref()
        {
            let _ = tx.send(SshCmd::Close);
            self.mark_exited();
            info!("SSH close command sent");
        }
    }

    /// 是否为 SSH 会话
    pub fn is_ssh(&self) -> bool {
        self.ssh_params.is_some()
    }

    /// Check if the child process has exited.
    pub fn is_exited(&self) -> bool {
        *self.exited.lock().unwrap_or_else(std::sync::PoisonError::into_inner)
    }

    /// Mark the session as exited.
    pub fn mark_exited(&self) {
        *self.exited.lock().unwrap_or_else(std::sync::PoisonError::into_inner) = true;
    }

    /// 同步写入输入数据（仅支持 Local backend）
    /// 用于现有的同步调用点，SSH backend 应使用 `write_input_async`
    ///
    /// # Errors
    /// Returns an error if the backend lock is held or the write fails.
    pub fn write_input_sync(&self, data: &[u8]) -> Result<(), String> {
        let Ok(mut backend) = self.backend.try_lock() else {
            return Err("backend lock held".into());
        };
        Self::write_input_locked(&mut backend, data)
    }

    /// Write input while waiting for the backend lock from a blocking thread.
    ///
    /// Callers MUST be inside `tokio::task::spawn_blocking` (or otherwise off-runtime), because
    /// `blocking_lock` panics when called on a Tokio worker thread. Waiting is intentional: a
    /// superseded connection's writer may wait and write its already-dequeued batch slightly late
    /// instead of failing fast.
    ///
    /// # Errors
    /// Returns an error if the backend is not local or the write fails.
    pub fn write_input_blocking(&self, data: &[u8]) -> Result<(), String> {
        let mut backend = self.backend.blocking_lock();
        Self::write_input_locked(&mut backend, data)
    }

    fn write_input_locked(backend: &mut SessionBackend, data: &[u8]) -> Result<(), String> {
        match &mut *backend {
            SessionBackend::Local { writer, .. } => {
                writer.write_all(data).map_err(|e| e.to_string())?;
                writer.flush().map_err(|e| e.to_string())?;
                Ok(())
            }
            SessionBackend::Ssh => Err("use write_input_async for SSH sessions".into()),
            SessionBackend::Exited => Err("session exited".into()),
        }
    }

    /// Resize the PTY and virtual screen. Consolidates three mutex acquisitions
    /// that were previously duplicated across Tauri and WS call sites.
    ///
    /// # Errors
    /// Returns an error if the PTY resize operation fails.
    pub fn resize(&self, cols: u16, rows: u16) -> Result<(), String> {
        if self.is_exited() {
            return Ok(());
        }
        if let Ok(mut backend) = self.backend.try_lock() {
            if let SessionBackend::Local { master, .. } = &mut *backend {
                use portable_pty::PtySize;
                master
                    .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
                    .map_err(|e| e.to_string())?;
            }
        }
        *self.size.lock().unwrap_or_else(std::sync::PoisonError::into_inner) = (cols, rows);
        self.screen
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .resize(cols as usize, rows as usize);
        Ok(())
    }

    /// 异步 resize，支持 SSH channel
    ///
    /// # Errors
    /// Returns an error if the resize operation fails.
    pub async fn resize_async(&self, cols: u16, rows: u16) -> Result<(), String> {
        if self.is_exited() {
            return Ok(());
        }
        // SSH: send resize command to reader task (owns the channel)
        if self.is_ssh() {
            if let Some(tx) =
                self.ssh_cmd_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref()
            {
                let _ = tx.send(SshCmd::Resize(cols, rows));
            }
        } else {
            let mut backend = self.backend.lock().await;
            match &mut *backend {
                SessionBackend::Local { master, .. } => {
                    use portable_pty::PtySize;
                    master
                        .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
                        .map_err(|e| e.to_string())?;
                }
                SessionBackend::Ssh | SessionBackend::Exited => {}
            }
        }
        *self.size.lock().unwrap_or_else(std::sync::PoisonError::into_inner) = (cols, rows);
        self.screen
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .resize(cols as usize, rows as usize);
        Ok(())
    }

    /// Fit-then-snapshot handshake (proposal 3): resize PTY + size + screen to
    /// the client's requested (cols, rows), then in one critical section take
    /// the scrollback + snapshot and enqueue `ReplayBegin` + chunks + `ReplayEnd`
    /// directly to the target client's mpsc channel, then clear its
    /// `snapshot_pending` flag so future `broadcast()` Output is delivered
    /// normally (and lands after `ReplayEnd` due to mpsc FIFO).
    ///
    /// Wire order per client: [`ReplayBegin`] -> [scrollback chunks] -> [snapshot]
    /// -> [`ReplayEnd`] -> [post-snapshot live Output]. Frontend diverts the
    /// chunks into its transaction buffer and writes them to xterm as a single
    /// batch on `ReplayEnd`, eliminating the settle-ladder / `ResizeObserver`
    /// mid-write interrupts that caused refresh-misalign (P2).
    ///
    /// Holding the clients lock blocks concurrent `broadcast()` from enqueuing
    /// to this client during the snapshot sequence; holding the screen lock
    /// blocks PTY reader from feeding new bytes during `snapshot()`. Bytes that
    /// were already in `output_rx` when this method started MAY be processed by
    /// broadcast after we release - their effect is in the snapshot, so the
    /// client could double-paint them briefly. Full dedup requires the seq
    /// system (proposal 2); MV accepts the rare glitch.
    ///
    /// # Errors
    /// Returns an error if PTY resize fails or the client has disconnected.
    pub async fn atomic_resize_and_snapshot_for_client(
        &self,
        client_id: u64,
        cols: u16,
        rows: u16,
    ) -> Result<(), String> {
        // PTY + size + screen resize (async - uses backend lock). Resize also
        // breaks sync mode if active (apply_and_broadcast_resize / Step 1b),
        // but resize_async does not break sync itself - handle that here.
        if self.is_sync_active() {
            self.set_sync_mode(false);
        }
        self.resize_async(cols, rows).await?;

        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|c| !c.tx.is_closed());
        let Some(client) = clients.iter().find(|c| c.id == client_id) else {
            return Err("snapshot target client not found or disconnected".into());
        };
        let tx = client.tx.clone();

        // Snapshot under screen lock (blocks PTY reader from feeding mid-snapshot).
        let (scrollback_chunks, snapshot) = {
            let screen = self.screen.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            let chunks = screen.snapshot_scrollback_chunks(200);
            let snap = screen.snapshot_for_replay();
            (chunks, snap)
        };

        // Enqueue replay sequence directly to the client's mpsc::Sender.
        // Bypasses send_chunk_to_clients' snapshot_pending check - control
        // events and snapshot chunks must reach the client even while pending.
        let _ = tx.try_send(SessionClientEvent::ReplayBegin { cols, rows });
        for chunk in scrollback_chunks {
            let _ = tx.try_send(SessionClientEvent::Output(chunk));
        }
        let _ = tx.try_send(SessionClientEvent::Output(snapshot));
        let _ = tx.try_send(SessionClientEvent::ReplayEnd);

        // Clear snapshot_pending AFTER ReplayEnd is enqueued. broadcast() that
        // runs after we release the clients lock will see snapshot_pending=false
        // and enqueue post-snapshot Output normally - it lands after ReplayEnd
        // in the mpsc FIFO, preserving wire order.
        if let Some(client) = clients.iter().find(|c| c.id == client_id) {
            client.snapshot_pending.store(false, Ordering::Relaxed);
        }

        Ok(())
    }

    /// 异步写入输入数据到后端
    ///
    /// # Errors
    /// Returns an error if the write operation fails.
    pub async fn write_input_async(&self, data: &[u8]) -> Result<(), String> {
        // SSH: send input to reader task (owns the channel)
        if self.is_ssh() {
            if let Some(tx) =
                self.ssh_cmd_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref()
            {
                tx.send(SshCmd::Input(data.to_vec()))
                    .map_err(|_| "SSH cmd channel closed".to_string())?;
                return Ok(());
            }
            return Err("SSH session not initialized".into());
        }
        let mut backend = self.backend.lock().await;
        match &mut *backend {
            SessionBackend::Local { writer, .. } => {
                writer.write_all(data).map_err(|e| e.to_string())?;
                writer.flush().map_err(|e| e.to_string())?;
            }
            SessionBackend::Ssh => {}
            SessionBackend::Exited => return Err("session exited".into()),
        }
        Ok(())
    }

    /// Debounced resize: coalesces rapid calls (e.g. window drag) and applies
    /// the latest size after a 25ms quiet period. Ensures the final resize is
    /// always applied even if no further calls arrive.
    pub fn resize_debounced(&self, origin_id: u64, cols: u16, rows: u16) {
        tracing::debug!("resize_debounced: {cols}x{rows}");
        let _ = self.resize_tx.send(Some((origin_id, cols, rows)));
    }

    pub fn apply_and_broadcast_resize(&self, origin_id: u64, cols: u16, rows: u16) {
        // ghostty pattern (src/terminal/c/terminal.zig:483-485): resize breaks
        // synchronized output mode. The DEC 2026 spec explicitly allows the
        // terminal to end sync mode on resize, and doing so prevents the
        // buffer-stuck bug where a PTY that goes silent mid-sync (e.g. Claude
        // Code waiting on an API response during a window resize) leaves
        // synchronized output active forever and the client sees a frozen screen.
        //
        // We flush BEFORE resizing so clients receive the pre-resize buffered
        // output at the old dimensions, then the resize event, then
        // post-resize output at the new dimensions - coherent ordering.
        if self.is_sync_active() {
            tracing::debug!("apply_and_broadcast_resize: breaking sync mode for resize, pane=?");
            self.set_sync_mode(false);
        }

        {
            let mut clients =
                self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            clients.retain(|client| !client.tx.is_closed());
            if !clients.iter().any(|client| client.id == origin_id) {
                return;
            }
        }
        if self.resize(cols, rows).is_err() {
            return;
        }
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter().filter(|client| client.id != origin_id) {
            if client.tx.try_send(SessionClientEvent::Resize { cols, rows }).is_err() {
                tracing::debug!("broadcast: client channel full, dropping resize {cols}x{rows}");
            }
        }
    }

    pub fn clear_tauri_client_if(&self, id: u64) {
        let mut tauri_client_id =
            self.tauri_client_id.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if *tauri_client_id == Some(id) {
            *tauri_client_id = None;
        }
    }

    pub fn on_pty_output(&self, data: &[u8]) {
        let default_home = crate::platform::shell::home_dir();
        let remote_home_guard =
            self.remote_home.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let home = remote_home_guard.as_ref().unwrap_or(&default_home);
        let mut state = self.cwd_state.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let CwdState { ref mut cwd, ref mut sniff_buf } = *state;
        cwd::sniff_cwd_from_title_osc(sniff_buf, data, home, cwd);
    }

    /// Replace the input channel, closing the old one (if any) so the previous
    /// PTY write task exits. Returns the new receiver for the caller to spawn
    /// a write task on.
    pub fn replace_input_channel(&self) -> mpsc::UnboundedReceiver<String> {
        let (tx, rx) = mpsc::unbounded_channel();
        let old =
            self.input_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).replace(tx);
        drop(old); // close old sender -> old write task's recv() returns None
        rx
    }

    pub fn add_client(&self) -> (u64, mpsc::Receiver<SessionClientEvent>) {
        // Bounded channel with non-blocking try_send: messages are dropped when
        // full rather than blocking the PTY reader. Keeps the shell responsive.
        let (tx, rx) = mpsc::channel(10240);
        let id = self.next_client_id.fetch_add(1, Ordering::Relaxed);
        self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner).push(
            ClientEndpoint { id, tx, snapshot_pending: std::sync::atomic::AtomicBool::new(true) },
        );
        (id, rx)
    }

    pub fn remove_client(&self, id: u64) {
        self.clients
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .retain(|client| client.id != id);
    }

    /// Send a chunk to all clients via non-blocking `try_send`.
    /// Channel-full messages are dropped (not the client) to keep the PTY reader
    /// non-blocking. Closed channels are pruned. Clients with `snapshot_pending`
    /// = true are skipped - their Output is captured by the upcoming snapshot
    /// and sending it live would double-paint.
    fn send_chunk_to_clients(clients: &mut Vec<ClientEndpoint>, chunk: &str) {
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter() {
            if client.snapshot_pending.load(Ordering::Relaxed) {
                continue;
            }
            if client.tx.try_send(SessionClientEvent::Output(chunk.to_string())).is_err() {
                tracing::debug!(
                    "broadcast: client channel full, dropping chunk ({}B)",
                    chunk.len()
                );
            }
        }
    }

    pub fn broadcast(&self, msg: &str) {
        if self.is_exited() {
            return;
        }
        let mut sync = self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if sync.active {
            let len = msg.len();
            sync.buffer.push(msg.to_string());
            sync.bytes += len;
            if sync.bytes < SYNC_BUFFER_LIMIT {
                return;
            }
            self.flush_sync_buffer_locked(&mut sync);
            return;
        }
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        Self::send_chunk_to_clients(&mut clients, msg);
    }

    pub fn is_sync_active(&self) -> bool {
        self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner).active
    }

    /// Enable or disable synchronized output mode (DEC mode 2026).
    /// When enabling: mark the sync state active, then enqueue `SyncBegin` while
    /// holding the sync guard, so no subsequent Output can overtake it.
    /// When disabling: mark inactive, flush buffered Output, and enqueue
    /// `SyncEnd` while holding the same guard. A concurrent `broadcast()` then
    /// lands after `SyncEnd` in each client's mpsc channel.
    pub fn set_sync_mode(&self, active: bool) {
        let mut sync = self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if active {
            sync.active = true;
            self.enqueue_control(&SessionClientEvent::SyncBegin);
        } else {
            if !sync.active {
                return;
            }
            sync.active = false;
            self.flush_sync_buffer_locked(&mut sync);
            #[cfg(test)]
            if let Some(hook) = self
                .sync_disable_hook
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
                .take()
            {
                hook();
            }
            self.enqueue_control(&SessionClientEvent::SyncEnd);
        }
    }

    /// Enqueue a control event (SyncBegin/SyncEnd) to all connected clients.
    /// Channel-full events are dropped (not the client), matching
    /// `send_chunk_to_clients`' policy. Closed channels are pruned.
    fn enqueue_control(&self, event: &SessionClientEvent) {
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter() {
            if client.tx.try_send(event.clone()).is_err() {
                tracing::debug!("broadcast: client channel full, dropping control event");
            }
        }
    }

    /// Flush buffered output accumulated during synchronized output mode.
    /// Breaks large payloads into chunks at UTF-8 character boundaries to avoid
    /// freezing the frontend UI thread.
    pub fn flush_sync_buffer(&self) {
        let mut sync = self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        self.flush_sync_buffer_locked(&mut sync);
    }

    fn flush_sync_buffer_locked(&self, sync: &mut SyncState) {
        let data = std::mem::take(&mut sync.buffer);
        sync.bytes = 0;
        if data.is_empty() {
            return;
        }
        let combined = data.join("");
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let mut start = 0;
        while start < combined.len() {
            let mut end = (start + FLUSH_CHUNK_SIZE).min(combined.len());
            while end > start && !combined.is_char_boundary(end) {
                end -= 1;
            }
            Self::send_chunk_to_clients(&mut clients, &combined[start..end]);
            start = end;
        }
    }

    /// Mark the session exited and notify all connected clients.
    ///
    /// The exited transition is notification/backend state only. It is not a
    /// cleanup winner claim; `SessionManager::close_session` owns that claim.
    pub fn notify_exit_and_mark_exited(&self, pane_id: &str, exit_code: Option<i32>) -> bool {
        let newly_exited = {
            let mut exited = self.exited.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            let newly_exited = !*exited;
            *exited = true;
            newly_exited
        };
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter() {
            if client
                .tx
                .try_send(SessionClientEvent::SessionExit {
                    pane_id: pane_id.to_string(),
                    exit_code,
                })
                .is_err()
            {
                tracing::debug!("broadcast: client channel full, dropping session_exit");
            }
        }
        newly_exited
    }

    pub fn has_clients(&self) -> bool {
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        !clients.is_empty()
    }
}

impl Drop for Session {
    fn drop(&mut self) {
        self.kill_backend_sync();
    }
}

#[cfg(test)]
mod tests;

/// Session regressions that use a stub with `SessionBackend::Exited` to avoid
/// spawning a real PTY/child process.
#[cfg(test)]
mod session_stub_tests {
    use super::*;
    use crate::notification::NotificationBroadcast;
    use std::sync::atomic::AtomicU64;
    use std::sync::mpsc as std_mpsc;
    use std::time::Duration;

    fn stub_session() -> Arc<Session> {
        let (resize_tx, _resize_rx) = watch::channel(None);
        let (output_tx, output_rx) = mpsc::unbounded_channel();
        Arc::new(Session {
            backend: tokio::sync::Mutex::new(SessionBackend::Exited),
            ssh_params: None,
            screen: Mutex::new(VirtualScreen::new(80, 24)),
            clients: Mutex::new(Vec::new()),
            next_client_id: AtomicU64::new(1),
            tauri_client_id: Mutex::new(None),
            input_tx: Mutex::new(None),
            status: Mutex::new(SessionStatus::Connected),
            is_connected: AtomicBool::new(true),
            size: Mutex::new((80, 24)),
            exited: Mutex::new(false),
            shell_type: "test".to_string(),
            tauri_on_exit: Mutex::new(None),
            cwd_state: Mutex::new(CwdState { cwd: PathBuf::from("/"), sniff_buf: Vec::new() }),
            sync: Mutex::new(SyncState::default()),
            sync_disable_hook: Mutex::new(None),
            resize_tx,
            ssh_cmd_tx: Mutex::new(None),
            ssh_handle: tokio::sync::Mutex::new(None),
            sftp_session: Mutex::new(None),
            remote_home: Mutex::new(None),
            remote_user: Mutex::new(None),
            output_tx,
            output_rx: Mutex::new(Some(output_rx)),
            pending_results: Mutex::new(Vec::new()),
        })
    }

    fn add_ready_client(session: &Session) -> mpsc::Receiver<SessionClientEvent> {
        let (client_id, rx) = session.add_client();
        let clients = session.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients
            .iter()
            .find(|client| client.id == client_id)
            .expect("newly added client must exist")
            .snapshot_pending
            .store(false, Ordering::Relaxed);
        rx
    }

    fn assert_output(event: SessionClientEvent, expected: &str) {
        match event {
            SessionClientEvent::Output(output) => assert_eq!(output, expected),
            _ => panic!("expected Output event"),
        }
    }

    #[test]
    fn layoutless_session_registration_adds_terminal_leaf_and_broadcasts() {
        let manager = SessionManager::new();
        let pane_id = "fallback-pane";
        let session = stub_session();
        manager.insert_session(pane_id.to_string(), Arc::clone(&session));
        let (_client_id, mut rx) = manager.add_sync_client();

        assert!(manager.register_singleton_tab(pane_id, &session, &session.shell_type));

        let tab = manager.tab_layouts.get(pane_id).expect("singleton tab must be registered");
        let layout = tab.get("layout").expect("singleton tab must contain a layout");
        assert_eq!(collect_terminal_leaf_pane_ids(layout), vec![pane_id]);
        assert_eq!(first_leaf_id(layout).as_deref(), Some(pane_id));
        drop(tab);

        let created: serde_json::Value =
            serde_json::from_str(&rx.try_recv().expect("tab_created must be broadcast")).unwrap();
        assert_eq!(created["type"], "tab_created");
        assert_eq!(created["tab_id"], pane_id);
        assert_eq!(created["pane_id"], pane_id);

        assert!(
            !manager.register_singleton_tab(pane_id, &session, &session.shell_type),
            "an existing terminal-leaf reference must not be duplicated"
        );
        assert!(rx.try_recv().is_err(), "no duplicate tab_created should be broadcast");

        assert!(manager.remove_tab(pane_id));
        assert!(
            manager.register_singleton_tab(pane_id, &session, &session.shell_type),
            "a live session missing its terminal-leaf reference must be repaired"
        );
        let repaired: serde_json::Value =
            serde_json::from_str(&rx.try_recv().expect("repair must broadcast tab_created"))
                .unwrap();
        assert_eq!(repaired["type"], "tab_created");
    }

    #[test]
    fn close_session_removes_singleton_tab_without_ghost() {
        let manager = SessionManager::new();
        let pane_id = "fallback-pane";
        let session = stub_session();
        manager.insert_session(pane_id.to_string(), Arc::clone(&session));
        let (_client_id, mut rx) = manager.add_sync_client();
        assert!(manager.register_singleton_tab(pane_id, &session, &session.shell_type));
        let _created = rx.try_recv().expect("tab_created must be broadcast");

        assert!(manager.close_session(pane_id, CloseReason::NaturalExit, false, Some(0)));
        assert!(!manager.sessions.contains_key(pane_id));
        assert!(!manager.tab_layouts.contains_key(pane_id));
        assert!(!manager
            .tab_order
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .iter()
            .any(|tab_id| tab_id == pane_id));

        let closed: serde_json::Value =
            serde_json::from_str(&rx.try_recv().expect("tab_closed must be broadcast")).unwrap();
        assert_eq!(closed["type"], "tab_closed");
        assert_eq!(closed["pane_id"], pane_id);
        assert!(rx.try_recv().is_err(), "no ghost-tab layout update should follow closure");
    }

    #[test]
    fn reap_claim_removes_exact_detached_generation_under_lifecycle() {
        let manager = SessionManager::new();
        let pane_id = "reap-pane";
        let session = stub_session();
        assert!(manager.insert_session(pane_id.to_string(), Arc::clone(&session)));
        session.set_status(SessionStatus::Detached { since: std::time::Instant::now() });
        let since = std::time::Instant::now() - Duration::from_secs(61);
        manager.age_unowned_for_test(pane_id, since);

        assert!(manager.try_reap_session_for_test(
            pane_id,
            &session,
            since + Duration::from_secs(61)
        ));
        assert!(!manager.sessions.contains_key(pane_id));
    }

    #[test]
    fn layout_only_close_prunes_non_terminal_leaves_and_broadcasts() {
        let manager = SessionManager::new();
        let tab_id = "tools-tab";
        manager.update_layout(
            tab_id.to_string(),
            serde_json::json!({
                "layout": {
                    "type": "split",
                    "direction": "horizontal",
                    "children": [
                        {"type": "leaf", "paneId": "plugin-pane", "kind": "plugin"},
                        {"type": "leaf", "paneId": "web-pane", "kind": "web"}
                    ]
                },
                "active_pane_id": "plugin-pane"
            }),
            Some("plugin-pane".to_string()),
        );
        let (_client_id, mut rx) = manager.add_sync_client();

        assert!(manager.close_pane("plugin-pane"));
        let updated: serde_json::Value =
            serde_json::from_str(&rx.try_recv().expect("layout_updated must be broadcast"))
                .unwrap();
        assert_eq!(updated["type"], "layout_updated");
        assert_eq!(updated["pane_id"], tab_id);
        assert_eq!(updated["active_pane_id"], "web-pane");
        assert_eq!(
            manager
                .active_pane_id
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
                .as_deref(),
            None
        );

        assert!(manager.close_pane("web-pane"));
        let closed: serde_json::Value =
            serde_json::from_str(&rx.try_recv().expect("tab_closed must be broadcast")).unwrap();
        assert_eq!(closed["type"], "tab_closed");
        assert_eq!(closed["pane_id"], tab_id);
        assert!(!manager.tab_layouts.contains_key(tab_id));
    }

    #[test]
    fn stale_generation_cannot_replace_or_close_current_session() {
        let manager = Arc::new(SessionManager::new());
        let pane_id = "generation-pane";
        let current = stub_session();
        let stale = stub_session();
        let reservation = manager.reserve_session(pane_id).unwrap();
        assert!(manager.reserve_session(pane_id).is_err());
        assert!(!manager.insert_session(pane_id.to_string(), Arc::clone(&stale)));
        assert!(reservation.publish(Arc::clone(&current)));
        assert!(!manager.insert_session(pane_id.to_string(), Arc::clone(&stale)));

        assert!(!manager.close_session_for_session(
            pane_id,
            &stale,
            CloseReason::NaturalExit,
            false,
            Some(0)
        ));
        assert!(manager
            .sessions
            .get(pane_id)
            .is_some_and(|session| Arc::ptr_eq(session.value(), &current)));
    }

    #[test]
    fn flush_sync_buffer_preserves_multibyte_across_chunk_boundary() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);

        // 65535 'a's + `界` (3 bytes) + "tail" = 65542 bytes.
        // FLUSH_CHUNK_SIZE (65536) splits `界` mid-character.
        let input = format!("{}界tail", "a".repeat(FLUSH_CHUNK_SIZE - 1));
        {
            let mut sync = session.sync.lock().unwrap();
            sync.buffer.push(input.clone());
            sync.bytes += input.len();
        }

        session.flush_sync_buffer();

        let received: String = std::iter::from_fn(|| rx.try_recv().ok())
            .filter_map(|event| match event {
                SessionClientEvent::Output(data) => Some(data),
                _ => None,
            })
            .collect();
        assert!(
            !received.contains('\u{FFFD}'),
            "flushed output contains U+FFFD replacement character"
        );
        assert_eq!(received, input);
    }

    #[test]
    fn sync_wire_order_is_begin_buffer_end_live() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);

        session.set_sync_mode(true);
        session.broadcast("BUF");
        session.set_sync_mode(false);
        session.broadcast("LIVE");

        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncBegin)));
        assert_output(rx.try_recv().expect("buffered output"), "BUF");
        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncEnd)));
        assert_output(rx.try_recv().expect("live output"), "LIVE");
        assert!(matches!(rx.try_recv(), Err(mpsc::error::TryRecvError::Empty)));
    }

    #[test]
    fn sync_teardown_blocks_concurrent_broadcast_until_after_sync_end() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);
        session.set_sync_mode(true);
        session.broadcast("BUF");

        let weak_session = Arc::downgrade(&session);
        let (started_tx, started_rx) = std_mpsc::channel();
        let (finished_tx, finished_rx) = std_mpsc::channel();
        let thread_handle = Arc::new(Mutex::new(None));
        let hook_thread_handle = Arc::clone(&thread_handle);
        *session.sync_disable_hook.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
            Some(Box::new(move || {
                let broadcast_session = weak_session.upgrade().expect("session remains alive");
                let handle = std::thread::spawn(move || {
                    started_tx.send(()).expect("teardown hook remains alive");
                    broadcast_session.broadcast("LIVE");
                    let _ = finished_tx.send(());
                });
                *hook_thread_handle.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
                    Some(handle);

                started_rx
                    .recv_timeout(Duration::from_secs(1))
                    .expect("concurrent broadcaster must start");
                assert!(
                    matches!(
                        finished_rx.recv_timeout(Duration::from_millis(100)),
                        Err(std_mpsc::RecvTimeoutError::Timeout)
                    ),
                    "concurrent broadcast passed the sync guard before teardown completed"
                );
            }));

        session.set_sync_mode(false);
        thread_handle
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .take()
            .expect("hook spawned broadcaster")
            .join()
            .expect("concurrent broadcaster completed");

        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncBegin)));
        assert_output(rx.try_recv().expect("buffered output"), "BUF");
        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncEnd)));
        assert_output(rx.try_recv().expect("live output"), "LIVE");
        assert!(matches!(rx.try_recv(), Err(mpsc::error::TryRecvError::Empty)));
    }

    #[test]
    fn double_sync_disable_emits_exactly_one_sync_end() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);

        session.set_sync_mode(true);
        session.set_sync_mode(false);
        session.set_sync_mode(false);

        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncBegin)));
        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncEnd)));
        assert!(matches!(rx.try_recv(), Err(mpsc::error::TryRecvError::Empty)));
    }

    #[tokio::test]
    async fn kill_and_remove_notifies_attention_ledger_with_a_single_removal_delta() {
        let manager = Arc::new(SessionManager::new());
        let notifier = Arc::new(NotificationBroadcast::new(Arc::clone(&manager.sync_clients)));
        manager.register_notifier(Arc::clone(&notifier));

        let pane_id = "stub-pane";
        manager.insert_session(pane_id.to_string(), stub_session());
        // Seed the ledger with an event for the pane so pane_closed produces a removal delta.
        notifier.send_bell(pane_id);

        let (client_id, mut rx) = manager.add_sync_client();
        notifier.register_client(&client_id);
        // Drain the initial snapshot so the next message we read is the removal delta.
        let snapshot_msg = rx.recv().await.expect("snapshot must arrive on register");
        let snapshot_value: serde_json::Value = serde_json::from_str(&snapshot_msg).unwrap();
        assert_eq!(snapshot_value["type"], "snapshot");

        assert!(manager.kill_and_remove(pane_id));

        let msg = rx.recv().await.expect("removal delta must be broadcast");
        let delta_value: serde_json::Value = serde_json::from_str(&msg).unwrap();
        assert_eq!(
            delta_value["type"], "state_delta",
            "expected exactly one removal delta, got {delta_value:?}"
        );
        let panes = delta_value["panes"].as_array().expect("panes array");
        assert!(
            panes.iter().any(|p| p["paneId"] == pane_id && p["removed"] == true),
            "expected a removal delta for {pane_id}, got {panes:?}"
        );
        // Unified close also emits the layoutless TabClosed fallback, but the
        // attention ledger still emits exactly one removal delta.
        let tab_closed: serde_json::Value =
            serde_json::from_str(&rx.try_recv().expect("tab_closed must follow")).unwrap();
        assert_eq!(tab_closed["type"], "tab_closed");
        assert!(rx.try_recv().is_err(), "no further messages expected after the removal delta");
    }
}
