#![allow(clippy::too_many_lines)]
use crate::event_bus::EventBus;
use crate::settings::SshAuthMethod;
use crate::vt_screen::VirtualScreen;
use dashmap::DashMap;
use portable_pty::{Child, MasterPty};
use serde::Serialize;
use std::{
    io::Write,
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicU16, AtomicU64, Ordering},
        Arc, Mutex, OnceLock,
    },
    time::Instant,
};
use tokio::sync::{mpsc, watch};
use tracing::info;

/// SSH 会话参数，用于分屏时复用连接信息
#[derive(Clone, Debug)]
pub struct SshSessionParams {
    pub host: String,
    pub port: u16,
    pub username: String,
    pub auth_method: SshAuthMethod,
    pub default_command: Option<String>,
    /// The `SshProfile.id` when created from a saved profile. `None` for quick-connect.
    pub profile_id: Option<String>,
    /// Initial remote directory to `cd` into after the shell starts.
    /// When `None` or empty, the shell starts in the remote `$HOME`.
    pub initial_cwd: Option<String>,
}

/// Session 的传输后端
pub enum SessionBackend {
    /// 本地 PTY
    Local {
        writer: Box<dyn Write + Send>,
        master: Box<dyn MasterPty + Send>,
        child: Box<dyn Child + Send + Sync>,
    },
    /// SSH 远程连接 — channel 已移至 reader task，此处仅保留标记
    Ssh,
    /// Backend resources were already dropped after the child exited.
    Exited,
}

/// Commands sent from Session methods to the SSH reader/writer task.
pub enum SshCmd {
    /// Write input data to the SSH channel
    Input(Vec<u8>),
    /// Resize the SSH channel
    Resize(u16, u16),
    /// Close the SSH channel
    Close,
}

/// Force-flush buffered synchronized output at this limit (256KB).
/// Prevents massive single payloads that freeze the frontend UI thread.
const SYNC_BUFFER_LIMIT: usize = 256 * 1024;
/// Maximum size of a single chunk sent to clients during flush.
const FLUSH_CHUNK_SIZE: usize = 64 * 1024;

fn parse_reap_secs(raw: Option<String>) -> u64 {
    raw.and_then(|v| v.parse::<u64>().ok()).unwrap_or(5_400)
}

pub enum SessionStatus {
    Connected,
    Detached { since: Instant },
}

pub struct CwdState {
    pub cwd: PathBuf,
    pub sniff_buf: Vec<u8>,
}

#[derive(Default)]
pub struct SyncState {
    active: bool,
    buffer: Vec<String>,
    bytes: usize,
}

pub struct PendingCommandResult {
    pub exit_code: i32,
    pub duration_ms: u64,
    pub stdout: String,
    pub method: String,
}

#[derive(Clone)]
pub enum SessionClientEvent {
    Output(String),
    Resize {
        cols: u16,
        rows: u16,
    },
    SessionExit {
        pane_id: String,
    },
    /// DEC mode 2026 transaction boundary. `SyncBegin` is enqueued BEFORE any
    /// subsequent Output (which is buffered while synchronized output is
    /// active); `SyncEnd` is enqueued AFTER that buffer is drained, so the
    /// on-wire order is [buffered Output chunks] → `SyncEnd` → [post-sync live
    /// Output]. Frontend uses these to divert Output into a transaction buffer
    /// and write it to xterm as a single batch, eliminating per-chunk
    /// intermediate rAF repaints during a synchronized redraw.
    SyncBegin,
    SyncEnd,
    /// Snapshot replay transaction boundary (fit-then-snapshot handshake).
    /// `ReplayBegin` precedes scrollback+snapshot chunks generated by the
    /// server in `atomic_resize_and_snapshot`; `ReplayEnd` follows them. Same
    /// transaction-buffer mechanism as SyncBegin/End on the frontend.
    ReplayBegin {
        cols: u16,
        rows: u16,
    },
    ReplayEnd,
}

pub struct ClientEndpoint {
    pub id: u64,
    pub tx: mpsc::Sender<SessionClientEvent>,
    /// True between `add_client` (or `emit_join_sync`) and the moment the server
    /// finishes enqueuing ReplayBegin+chunks+ReplayEnd to this client. While
    /// true, `broadcast()` and `flush_sync_buffer()` drop Output chunks for this
    /// client (their effect is captured by the upcoming snapshot, so sending
    /// them live would double-paint). Control events (SyncBegin/SyncEnd,
    /// ReplayBegin/ReplayEnd) bypass this flag and always reach the client.
    pub snapshot_pending: std::sync::atomic::AtomicBool,
}

pub struct Session {
    /// 传输后端（本地 PTY 或 SSH）
    pub backend: tokio::sync::Mutex<SessionBackend>,
    /// SSH 会话参数（分屏时复用），None 表示本地会话
    pub ssh_params: Option<SshSessionParams>,
    pub screen: Mutex<VirtualScreen>,
    pub clients: Mutex<Vec<ClientEndpoint>>,
    pub next_client_id: AtomicU64,
    pub tauri_client_id: Mutex<Option<u64>>,
    pub input_tx: Mutex<Option<mpsc::UnboundedSender<String>>>,
    pub status: Mutex<SessionStatus>,
    pub size: Mutex<(u16, u16)>,
    pub exited: Mutex<bool>,
    #[allow(dead_code)]
    pub shell_type: String,
    #[allow(clippy::type_complexity)]
    pub tauri_on_exit: Mutex<Option<Arc<dyn Fn(String) + Send + Sync>>>,
    pub cwd_state: Mutex<CwdState>,
    /// DEC mode 2026 state. Always acquire this before `clients` when both are needed.
    pub sync: Mutex<SyncState>,
    #[cfg(test)]
    pub(crate) sync_disable_hook: Mutex<Option<Box<dyn FnOnce() + Send>>>,
    /// Sender for debounced resize requests (None = no pending resize)
    pub(crate) resize_tx: watch::Sender<Option<(u64, u16, u16)>>,
    /// Channel to send commands (input/resize/close) to the SSH reader task.
    /// None for local sessions.
    pub ssh_cmd_tx: Mutex<Option<mpsc::UnboundedSender<SshCmd>>>,
    /// SSH client handle for opening new channels (SFTP, exec).
    /// Type-erased to avoid circular deps. Actual type: `russh::client::Handle<ssh::SshClientHandler>`
    /// Uses `tokio::sync::Mutex` so the guard can be held across `.await` points.
    pub ssh_handle: tokio::sync::Mutex<Option<Box<dyn std::any::Any + Send + Sync>>>,
    /// Cached SFTP session for workspace operations. Created lazily.
    /// Actual type: `Arc<russh_sftp::client::SftpSession>`
    pub sftp_session: Mutex<Option<Box<dyn std::any::Any + Send + Sync>>>,
    /// Remote home directory for SSH sessions. Used for `~` expansion in
    /// CWD sniffing and workspace path resolution.
    /// `None` for local sessions.
    pub remote_home: Mutex<Option<PathBuf>>,
    /// Current PTY user for SSH sessions. Detects user switches (e.g. `su root`).
    /// When the PTY user differs from the SSH auth user, SFTP operations may
    /// fail due to permission issues, and SSH exec fallback with sudo is needed.
    /// `None` means not yet detected (lazy initialization on first workspace op).
    pub remote_user: Mutex<Option<String>>,
    /// Raw PTY output channel: reader sends raw bytes here for xterm.js rendering.
    /// Unbounded so the PTY reader never blocks on send.
    pub output_tx: mpsc::UnboundedSender<Vec<u8>>,
    /// Receiver side, taken once by the broadcast task.
    pub output_rx: Mutex<Option<mpsc::UnboundedReceiver<Vec<u8>>>>,
    /// Command results extracted during `feed()`, consumed by the broadcast task.
    pub pending_results: Mutex<Vec<PendingCommandResult>>,
}

impl Session {
    /// Explicitly kill the child process. Safe to call multiple times (idempotent).
    /// After this, the PTY reader task's `reader.read()` will return Err/Ok(0),
    /// causing it to exit and drop its `Arc<Session>`, which triggers `Drop`.
    pub fn kill_child(&self) {
        self.kill_backend_sync();
    }

    /// 同步清理后端（用于 `kill_child` 和 Drop）
    fn kill_backend_sync(&self) {
        let Ok(mut backend) = self.backend.try_lock() else {
            // 锁被持有（SSH async 操作中），跳过同步清理
            // SSH reader task 会在连接关闭时自行清理
            return;
        };
        match &mut *backend {
            SessionBackend::Local { child, .. } => {
                let pid = child.process_id();
                #[cfg(unix)]
                if let Some(pid) = pid {
                    #[allow(clippy::cast_possible_wrap)]
                    let process_group = pid as i32;
                    unsafe {
                        libc::killpg(process_group, libc::SIGTERM);
                    }
                    std::thread::sleep(std::time::Duration::from_millis(50));
                    unsafe {
                        libc::killpg(process_group, libc::SIGKILL);
                    }
                }
                let _ = child.kill();
                let _ = child.wait();
                self.mark_exited();
                info!("Session child killed: pid={:?}", pid);
            }
            SessionBackend::Ssh => {
                // SSH channel is owned by the reader task; signal it to close
                if let Some(tx) = self
                    .ssh_cmd_tx
                    .lock()
                    .unwrap_or_else(std::sync::PoisonError::into_inner)
                    .as_ref()
                {
                    let _ = tx.send(SshCmd::Close);
                }
                self.mark_exited();
                info!("SSH session marked as exited");
            }
            SessionBackend::Exited => {}
        }
    }

    /// 异步清理 SSH channel
    pub fn kill_backend_async(&self) {
        if let Some(tx) =
            self.ssh_cmd_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref()
        {
            let _ = tx.send(SshCmd::Close);
            self.mark_exited();
            info!("SSH close command sent");
        }
    }

    /// 是否为 SSH 会话
    pub fn is_ssh(&self) -> bool {
        self.ssh_params.is_some()
    }

    /// Check if the child process has exited.
    pub fn is_exited(&self) -> bool {
        *self.exited.lock().unwrap_or_else(std::sync::PoisonError::into_inner)
    }

    /// Mark the session as exited.
    pub fn mark_exited(&self) {
        *self.exited.lock().unwrap_or_else(std::sync::PoisonError::into_inner) = true;
    }

    /// 同步写入输入数据（仅支持 Local backend）
    /// 用于现有的同步调用点，SSH backend 应使用 `write_input_async`
    ///
    /// # Errors
    /// Returns an error if the backend lock is held or the write fails.
    pub fn write_input_sync(&self, data: &[u8]) -> Result<(), String> {
        let Ok(mut backend) = self.backend.try_lock() else {
            return Err("backend lock held".into());
        };
        match &mut *backend {
            SessionBackend::Local { writer, .. } => {
                writer.write_all(data).map_err(|e| e.to_string())?;
                writer.flush().map_err(|e| e.to_string())?;
                Ok(())
            }
            SessionBackend::Ssh => Err("use write_input_async for SSH sessions".into()),
            SessionBackend::Exited => Err("session exited".into()),
        }
    }

    /// Resize the PTY and virtual screen. Consolidates three mutex acquisitions
    /// that were previously duplicated across Tauri and WS call sites.
    ///
    /// # Errors
    /// Returns an error if the PTY resize operation fails.
    pub fn resize(&self, cols: u16, rows: u16) -> Result<(), String> {
        if self.is_exited() {
            return Ok(());
        }
        if let Ok(mut backend) = self.backend.try_lock() {
            if let SessionBackend::Local { master, .. } = &mut *backend {
                use portable_pty::PtySize;
                master
                    .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
                    .map_err(|e| e.to_string())?;
            }
        }
        *self.size.lock().unwrap_or_else(std::sync::PoisonError::into_inner) = (cols, rows);
        self.screen
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .resize(cols as usize, rows as usize);
        Ok(())
    }

    /// 异步 resize，支持 SSH channel
    ///
    /// # Errors
    /// Returns an error if the resize operation fails.
    pub async fn resize_async(&self, cols: u16, rows: u16) -> Result<(), String> {
        if self.is_exited() {
            return Ok(());
        }
        // SSH: send resize command to reader task (owns the channel)
        if self.is_ssh() {
            if let Some(tx) =
                self.ssh_cmd_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref()
            {
                let _ = tx.send(SshCmd::Resize(cols, rows));
            }
        } else {
            let mut backend = self.backend.lock().await;
            match &mut *backend {
                SessionBackend::Local { master, .. } => {
                    use portable_pty::PtySize;
                    master
                        .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
                        .map_err(|e| e.to_string())?;
                }
                SessionBackend::Ssh | SessionBackend::Exited => {}
            }
        }
        *self.size.lock().unwrap_or_else(std::sync::PoisonError::into_inner) = (cols, rows);
        self.screen
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .resize(cols as usize, rows as usize);
        Ok(())
    }

    /// Fit-then-snapshot handshake (proposal 3): resize PTY + size + screen to
    /// the client's requested (cols, rows), then in one critical section take
    /// the scrollback + snapshot and enqueue `ReplayBegin` + chunks + `ReplayEnd`
    /// directly to the target client's mpsc channel, then clear its
    /// `snapshot_pending` flag so future `broadcast()` Output is delivered
    /// normally (and lands after `ReplayEnd` due to mpsc FIFO).
    ///
    /// Wire order per client: [`ReplayBegin`] → [scrollback chunks] → [snapshot]
    /// → [`ReplayEnd`] → [post-snapshot live Output]. Frontend diverts the
    /// chunks into its transaction buffer and writes them to xterm as a single
    /// batch on `ReplayEnd`, eliminating the settle-ladder / `ResizeObserver`
    /// mid-write interrupts that caused refresh-misalign (P2).
    ///
    /// Holding the clients lock blocks concurrent `broadcast()` from enqueuing
    /// to this client during the snapshot sequence; holding the screen lock
    /// blocks PTY reader from feeding new bytes during `snapshot()`. Bytes that
    /// were already in `output_rx` when this method started MAY be processed by
    /// broadcast after we release — their effect is in the snapshot, so the
    /// client could double-paint them briefly. Full dedup requires the seq
    /// system (proposal 2); MV accepts the rare glitch.
    ///
    /// # Errors
    /// Returns an error if PTY resize fails or the client has disconnected.
    pub async fn atomic_resize_and_snapshot_for_client(
        &self,
        client_id: u64,
        cols: u16,
        rows: u16,
    ) -> Result<(), String> {
        // PTY + size + screen resize (async — uses backend lock). Resize also
        // breaks sync mode if active (apply_and_broadcast_resize / Step 1b),
        // but resize_async does not break sync itself — handle that here.
        if self.is_sync_active() {
            self.set_sync_mode(false);
        }
        self.resize_async(cols, rows).await?;

        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|c| !c.tx.is_closed());
        let Some(client) = clients.iter().find(|c| c.id == client_id) else {
            return Err("snapshot target client not found or disconnected".into());
        };
        let tx = client.tx.clone();

        // Snapshot under screen lock (blocks PTY reader from feeding mid-snapshot).
        let (scrollback_chunks, snapshot) = {
            let screen = self.screen.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            let chunks = screen.snapshot_scrollback_chunks(200);
            let snap = screen.snapshot_for_replay();
            (chunks, snap)
        };

        // Enqueue replay sequence directly to the client's mpsc::Sender.
        // Bypasses send_chunk_to_clients' snapshot_pending check — control
        // events and snapshot chunks must reach the client even while pending.
        let _ = tx.try_send(SessionClientEvent::ReplayBegin { cols, rows });
        for chunk in scrollback_chunks {
            let _ = tx.try_send(SessionClientEvent::Output(chunk));
        }
        let _ = tx.try_send(SessionClientEvent::Output(snapshot));
        let _ = tx.try_send(SessionClientEvent::ReplayEnd);

        // Clear snapshot_pending AFTER ReplayEnd is enqueued. broadcast() that
        // runs after we release the clients lock will see snapshot_pending=false
        // and enqueue post-snapshot Output normally — it lands after ReplayEnd
        // in the mpsc FIFO, preserving wire order.
        if let Some(client) = clients.iter().find(|c| c.id == client_id) {
            client.snapshot_pending.store(false, Ordering::Relaxed);
        }

        Ok(())
    }

    /// 异步写入输入数据到后端
    ///
    /// # Errors
    /// Returns an error if the write operation fails.
    pub async fn write_input_async(&self, data: &[u8]) -> Result<(), String> {
        // SSH: send input to reader task (owns the channel)
        if self.is_ssh() {
            if let Some(tx) =
                self.ssh_cmd_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref()
            {
                tx.send(SshCmd::Input(data.to_vec()))
                    .map_err(|_| "SSH cmd channel closed".to_string())?;
                return Ok(());
            }
            return Err("SSH session not initialized".into());
        }
        let mut backend = self.backend.lock().await;
        match &mut *backend {
            SessionBackend::Local { writer, .. } => {
                writer.write_all(data).map_err(|e| e.to_string())?;
                writer.flush().map_err(|e| e.to_string())?;
            }
            SessionBackend::Ssh => {}
            SessionBackend::Exited => return Err("session exited".into()),
        }
        Ok(())
    }

    /// Debounced resize: coalesces rapid calls (e.g. window drag) and applies
    /// the latest size after a 25ms quiet period. Ensures the final resize is
    /// always applied even if no further calls arrive.
    pub fn resize_debounced(&self, origin_id: u64, cols: u16, rows: u16) {
        tracing::debug!("resize_debounced: {cols}x{rows}");
        let _ = self.resize_tx.send(Some((origin_id, cols, rows)));
    }

    pub fn apply_and_broadcast_resize(&self, origin_id: u64, cols: u16, rows: u16) {
        // ghostty pattern (src/terminal/c/terminal.zig:483-485): resize breaks
        // synchronized output mode. The DEC 2026 spec explicitly allows the
        // terminal to end sync mode on resize, and doing so prevents the
        // buffer-stuck bug where a PTY that goes silent mid-sync (e.g. Claude
        // Code waiting on an API response during a window resize) leaves
        // synchronized output active forever and the client sees a frozen screen.
        //
        // We flush BEFORE resizing so clients receive the pre-resize buffered
        // output at the old dimensions, then the resize event, then
        // post-resize output at the new dimensions — coherent ordering.
        if self.is_sync_active() {
            tracing::debug!("apply_and_broadcast_resize: breaking sync mode for resize, pane=?");
            self.set_sync_mode(false);
        }

        {
            let mut clients =
                self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            clients.retain(|client| !client.tx.is_closed());
            if !clients.iter().any(|client| client.id == origin_id) {
                return;
            }
        }
        if self.resize(cols, rows).is_err() {
            return;
        }
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter().filter(|client| client.id != origin_id) {
            if client.tx.try_send(SessionClientEvent::Resize { cols, rows }).is_err() {
                tracing::debug!("broadcast: client channel full, dropping resize {cols}x{rows}");
            }
        }
    }

    pub fn clear_tauri_client_if(&self, id: u64) {
        let mut tauri_client_id =
            self.tauri_client_id.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if *tauri_client_id == Some(id) {
            *tauri_client_id = None;
        }
    }

    pub fn on_pty_output(&self, data: &[u8]) {
        let default_home = crate::platform::shell::home_dir();
        let remote_home_guard =
            self.remote_home.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let home = remote_home_guard.as_ref().unwrap_or(&default_home);
        let mut state = self.cwd_state.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let CwdState { ref mut cwd, ref mut sniff_buf } = *state;
        sniff_cwd_from_title_osc(sniff_buf, data, home, cwd);
    }

    /// Replace the input channel, closing the old one (if any) so the previous
    /// PTY write task exits. Returns the new receiver for the caller to spawn
    /// a write task on.
    pub fn replace_input_channel(&self) -> mpsc::UnboundedReceiver<String> {
        let (tx, rx) = mpsc::unbounded_channel();
        let old =
            self.input_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).replace(tx);
        drop(old); // close old sender → old write task's recv() returns None
        rx
    }

    pub fn add_client(&self) -> (u64, mpsc::Receiver<SessionClientEvent>) {
        // Bounded channel with non-blocking try_send: messages are dropped when
        // full rather than blocking the PTY reader. Keeps the shell responsive.
        let (tx, rx) = mpsc::channel(10240);
        let id = self.next_client_id.fetch_add(1, Ordering::Relaxed);
        self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner).push(
            ClientEndpoint { id, tx, snapshot_pending: std::sync::atomic::AtomicBool::new(true) },
        );
        (id, rx)
    }

    pub fn remove_client(&self, id: u64) {
        self.clients
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .retain(|client| client.id != id);
    }

    /// Send a chunk to all clients via non-blocking `try_send`.
    /// Channel-full messages are dropped (not the client) to keep the PTY reader
    /// non-blocking. Closed channels are pruned. Clients with `snapshot_pending`
    /// = true are skipped — their Output is captured by the upcoming snapshot
    /// and sending it live would double-paint.
    fn send_chunk_to_clients(clients: &mut Vec<ClientEndpoint>, chunk: &str) {
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter() {
            if client.snapshot_pending.load(Ordering::Relaxed) {
                continue;
            }
            if client.tx.try_send(SessionClientEvent::Output(chunk.to_string())).is_err() {
                tracing::debug!(
                    "broadcast: client channel full, dropping chunk ({}B)",
                    chunk.len()
                );
            }
        }
    }

    pub fn broadcast(&self, msg: &str) {
        if self.is_exited() {
            return;
        }
        let mut sync = self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if sync.active {
            let len = msg.len();
            sync.buffer.push(msg.to_string());
            sync.bytes += len;
            if sync.bytes < SYNC_BUFFER_LIMIT {
                return;
            }
            self.flush_sync_buffer_locked(&mut sync);
            return;
        }
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        Self::send_chunk_to_clients(&mut clients, msg);
    }

    pub fn is_sync_active(&self) -> bool {
        self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner).active
    }

    /// Enable or disable synchronized output mode (DEC mode 2026).
    /// When enabling: mark the sync state active, then enqueue `SyncBegin` while
    /// holding the sync guard, so no subsequent Output can overtake it.
    /// When disabling: mark inactive, flush buffered Output, and enqueue
    /// `SyncEnd` while holding the same guard. A concurrent `broadcast()` then
    /// lands after `SyncEnd` in each client's mpsc channel.
    pub fn set_sync_mode(&self, active: bool) {
        let mut sync = self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if active {
            sync.active = true;
            self.enqueue_control(&SessionClientEvent::SyncBegin);
        } else {
            if !sync.active {
                return;
            }
            sync.active = false;
            self.flush_sync_buffer_locked(&mut sync);
            #[cfg(test)]
            if let Some(hook) = self
                .sync_disable_hook
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
                .take()
            {
                hook();
            }
            self.enqueue_control(&SessionClientEvent::SyncEnd);
        }
    }

    /// Enqueue a control event (SyncBegin/SyncEnd) to all connected clients.
    /// Channel-full events are dropped (not the client), matching
    /// `send_chunk_to_clients`' policy. Closed channels are pruned.
    fn enqueue_control(&self, event: &SessionClientEvent) {
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter() {
            if client.tx.try_send(event.clone()).is_err() {
                tracing::debug!("broadcast: client channel full, dropping control event");
            }
        }
    }

    /// Flush buffered output accumulated during synchronized output mode.
    /// Breaks large payloads into chunks to avoid freezing the frontend UI thread.
    pub fn flush_sync_buffer(&self) {
        let mut sync = self.sync.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        self.flush_sync_buffer_locked(&mut sync);
    }

    fn flush_sync_buffer_locked(&self, sync: &mut SyncState) {
        let data = std::mem::take(&mut sync.buffer);
        sync.bytes = 0;
        if data.is_empty() {
            return;
        }
        let combined = data.join("");
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if combined.len() <= FLUSH_CHUNK_SIZE {
            Self::send_chunk_to_clients(&mut clients, &combined);
        } else {
            for chunk in combined.as_bytes().chunks(FLUSH_CHUNK_SIZE) {
                let s = String::from_utf8_lossy(chunk).into_owned();
                Self::send_chunk_to_clients(&mut clients, &s);
            }
        }
    }

    /// Notify all connected clients that the session is exiting, then mark as exited.
    /// Returns false when another cleanup path already handled the exit.
    pub fn notify_exit_and_mark_exited(&self, pane_id: &str) -> bool {
        {
            let mut exited = self.exited.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            if *exited {
                return false;
            }
            *exited = true;
        }
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        for client in clients.iter() {
            if client
                .tx
                .try_send(SessionClientEvent::SessionExit { pane_id: pane_id.to_string() })
                .is_err()
            {
                tracing::debug!("broadcast: client channel full, dropping session_exit");
            }
        }
        true
    }

    pub fn has_clients(&self) -> bool {
        let mut clients = self.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|client| !client.tx.is_closed());
        !clients.is_empty()
    }
}

impl Drop for Session {
    fn drop(&mut self) {
        self.kill_backend_sync();
    }
}

const OSC_SNIFF_CAP: usize = 32768;

fn sniff_cwd_from_title_osc(buf: &mut Vec<u8>, chunk: &[u8], home: &Path, cwd: &mut PathBuf) {
    buf.extend_from_slice(chunk);
    if buf.len() > OSC_SNIFF_CAP {
        let drop = buf.len() - OSC_SNIFF_CAP;
        buf.drain(..drop);
    }
    let needle = b"\x1b]0;";
    while let Some(i) = find_subslice(buf, needle) {
        let payload_start = i + needle.len();
        let bel_pos = buf[payload_start..].iter().position(|&b| b == 0x07);
        let st_pos = buf[payload_start..].windows(2).position(|w| w == b"\x1b\\");
        let rel = match (bel_pos, st_pos) {
            (Some(a), Some(b)) => a.min(b),
            (Some(a), None) => a,
            (None, Some(b)) => b,
            (None, None) => break,
        };
        let terminator_len = if st_pos == Some(rel) { 2 } else { 1 };
        let title_end = payload_start + rel;
        let title = String::from_utf8_lossy(&buf[payload_start..title_end]);
        if let Some(p) = parse_title_cwd(&title, home) {
            // canonicalize resolves symlinks on the local filesystem. For SSH
            // sessions the path is remote and canonicalize fails - fall back
            // to the raw path so cwd tracking still works.
            *cwd = p.canonicalize().unwrap_or(p);
        }
        buf.drain(..title_end + terminator_len);
    }
}

fn find_subslice(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|window| window == needle)
}

#[must_use]
pub fn collect_leaf_pane_ids(layout: &serde_json::Value) -> Vec<String> {
    let mut ids = Vec::new();
    collect_leaf_ids_recursive(layout, &mut ids);
    ids
}

/// # Panics
/// May panic if the JSON tree structure is unexpectedly malformed.
#[must_use]
pub fn remove_pane_from_layout(
    node: &serde_json::Value,
    pane_id: &str,
) -> Option<serde_json::Value> {
    let node_type = node.get("type")?.as_str()?;
    match node_type {
        "leaf" => {
            if node.get("paneId")?.as_str()? == pane_id {
                None
            } else {
                Some(node.clone())
            }
        }
        "split" => {
            let children = node.get("children")?.as_array()?;
            let new_children: Vec<serde_json::Value> =
                children.iter().filter_map(|c| remove_pane_from_layout(c, pane_id)).collect();
            match new_children.len() {
                0 => None,
                _ if new_children.len() == children.len() => {
                    // Children count unchanged — but a child may have changed internally
                    // (e.g. a nested split collapsed). Always use the updated children.
                    let mut result = node.clone();
                    result["children"] = serde_json::Value::Array(new_children);
                    Some(result)
                }
                1 => {
                    // Single-child split is degenerate — collapse by returning the child directly
                    Some(
                        new_children
                            .into_iter()
                            .next()
                            .unwrap_or_else(|| unreachable!("checked len == 1")),
                    )
                }
                _ => {
                    let mut result = node.clone();
                    result["children"] = serde_json::Value::Array(new_children);
                    // Rebalance ratios evenly
                    let n = result["children"]
                        .as_array()
                        .unwrap_or_else(|| unreachable!("just assigned as array"))
                        .len();
                    #[allow(clippy::cast_precision_loss)]
                    let ratio = 1.0 / f64::from(u32::try_from(n).unwrap_or(1));
                    result["ratios"] = serde_json::Value::Array(
                        (0..n).map(|_| serde_json::Value::from(ratio)).collect(),
                    );
                    Some(result)
                }
            }
        }
        _ => Some(node.clone()),
    }
}

/// Find and return a clone of the leaf node matching `pane_id`, preserving
/// all its original fields (kind, pluginId, path, url, title, etc.).
/// Used by move/extract handlers to relocate an existing leaf verbatim.
#[must_use]
pub fn extract_leaf_from_layout(
    node: &serde_json::Value,
    pane_id: &str,
) -> Option<serde_json::Value> {
    let node_type = node.get("type")?.as_str()?;
    match node_type {
        "leaf" => {
            if node.get("paneId")?.as_str()? == pane_id {
                Some(node.clone())
            } else {
                None
            }
        }
        "split" => {
            let children = node.get("children")?.as_array()?;
            children.iter().find_map(|c| extract_leaf_from_layout(c, pane_id))
        }
        _ => None,
    }
}

fn collect_leaf_ids_recursive(node: &serde_json::Value, ids: &mut Vec<String>) {
    if let Some(node_type) = node.get("type").and_then(|v| v.as_str()) {
        if node_type == "leaf" {
            if let Some(pane_id) = node.get("paneId").and_then(|v| v.as_str()) {
                ids.push(pane_id.to_string());
            }
        } else if node_type == "split" {
            if let Some(children) = node.get("children").and_then(|v| v.as_array()) {
                for child in children {
                    collect_leaf_ids_recursive(child, ids);
                }
            }
        }
    }
}

/// Returns the kind of a leaf node, defaulting to `"terminal"` when absent
/// (for backward compatibility with layouts created before `kind` was introduced).
fn leaf_kind(node: &serde_json::Value) -> &str {
    node.get("kind").and_then(|v| v.as_str()).unwrap_or("terminal")
}

/// Collect `pane_ids` of leaves that require a PTY session (`kind=terminal` or absent).
/// Leaves with `kind=plugin|files|web` have no PTY and are excluded.
#[must_use]
pub fn collect_terminal_leaf_pane_ids(layout: &serde_json::Value) -> Vec<String> {
    let mut ids = Vec::new();
    collect_terminal_leaf_ids_recursive(layout, &mut ids);
    ids
}

fn collect_terminal_leaf_ids_recursive(node: &serde_json::Value, ids: &mut Vec<String>) {
    if let Some(node_type) = node.get("type").and_then(|v| v.as_str()) {
        if node_type == "leaf" {
            if leaf_kind(node) == "terminal" {
                if let Some(pane_id) = node.get("paneId").and_then(|v| v.as_str()) {
                    ids.push(pane_id.to_string());
                }
            }
        } else if node_type == "split" {
            if let Some(children) = node.get("children").and_then(|v| v.as_array()) {
                for child in children {
                    collect_terminal_leaf_ids_recursive(child, ids);
                }
            }
        }
    }
}

/// Recursively ensure every leaf node carries a `kind` field. Leaves without
/// `kind` are tagged `"terminal"` (backward compatibility). Returns a new tree.
#[must_use]
pub fn ensure_leaf_kind(layout: serde_json::Value) -> serde_json::Value {
    match layout.get("type").and_then(|v| v.as_str()) {
        Some("leaf") => {
            if layout.get("kind").is_none() {
                let mut result = layout;
                if let Some(obj) = result.as_object_mut() {
                    obj.insert("kind".to_string(), serde_json::json!("terminal"));
                }
                result
            } else {
                layout
            }
        }
        Some("split") => {
            let mut result = layout;
            if let Some(children) = result.get_mut("children").and_then(|c| c.as_array_mut()) {
                let new_children: Vec<serde_json::Value> =
                    children.drain(..).map(ensure_leaf_kind).collect();
                *children = new_children;
            }
            result
        }
        _ => layout,
    }
}

/// Normalize a split `direction` field to `"horizontal"` / `"vertical"`.
///
/// Frontend's `SplitContainer` and `SplitDivider` only handle these two values.
/// Legacy callers (cross-tab merge, non-terminal pane insertion) pass
/// `"left"` / `"right"` / `"top"` / `"bottom"` to express position; that
/// position is used to decide child ordering, but the stored `direction`
/// field must be the axis. This helper also tolerates `"horizontal"` /
/// `"vertical"` inputs so callers can pass either form.
fn normalize_split_direction(direction: &str) -> &'static str {
    match direction {
        "top" | "bottom" | "vertical" => "vertical",
        _ => "horizontal",
    }
}

/// Insert a new pane into the layout tree by splitting the target pane.
/// Returns the updated layout, or None if the target pane was not found.
#[must_use]
#[allow(clippy::cast_precision_loss)]
pub fn insert_pane_into_layout(
    layout: &serde_json::Value,
    target_pane_id: &str,
    direction: &str,
    new_pane_id: &str,
) -> Option<serde_json::Value> {
    insert_pane_into_layout_inner(layout, target_pane_id, direction, new_pane_id, None, None)
}

/// Insert a subtree (split or leaf) into the layout by splitting the target
/// pane. The target leaf is wrapped in a new split node containing
/// `[subtree, target]` when `direction=left|top` (subtree first), or
/// `[target, subtree]` otherwise. The subtree's internal structure is
/// preserved as-is. Used for "drag whole tab as subtree" (mode A).
///
/// When the parent split has the same `direction` as the new split, the new
/// split's children are flattened into the parent (mirrors
/// `insert_pane_into_layout_inner` behavior).
#[must_use]
#[allow(clippy::cast_precision_loss)]
pub fn insert_subtree_into_layout(
    layout: &serde_json::Value,
    target_pane_id: &str,
    direction: &str,
    subtree: serde_json::Value,
) -> Option<serde_json::Value> {
    let node_type = layout.get("type")?.as_str()?;
    match node_type {
        "leaf" => {
            let pane_id = layout.get("paneId")?.as_str()?;
            if pane_id == target_pane_id {
                let existing_leaf = layout.clone();
                let split_id = uuid::Uuid::new_v4().to_string();
                let (first, second) = match direction {
                    "left" | "top" => (subtree, existing_leaf),
                    _ => (existing_leaf, subtree),
                };
                Some(serde_json::json!({
                    "type": "split",
                    "id": split_id,
                    "direction": normalize_split_direction(direction),
                    "children": [first, second],
                    "ratios": [0.5, 0.5],
                }))
            } else {
                Some(layout.clone())
            }
        }
        "split" => {
            let parent_dir = layout.get("direction")?.as_str()?;
            let parent_dir_axis = normalize_split_direction(parent_dir);
            let children = layout.get("children")?.as_array()?;
            let mut new_children: Vec<serde_json::Value> = Vec::new();
            let mut found = false;
            for child in children {
                if let Some(updated) =
                    insert_subtree_into_layout(child, target_pane_id, direction, subtree.clone())
                {
                    let changed = found || updated != *child;
                    if changed {
                        found = true;
                    }
                    // Flatten: if the updated child became a split with the same
                    // direction as the parent, splice its children into the parent.
                    if changed
                        && updated.get("type").and_then(|t| t.as_str()) == Some("split")
                        && updated
                            .get("direction")
                            .and_then(|d| d.as_str())
                            .map(normalize_split_direction)
                            == Some(parent_dir_axis)
                    {
                        if let Some(inner_children) =
                            updated.get("children").and_then(|c| c.as_array())
                        {
                            new_children.extend(inner_children.iter().cloned());
                            continue;
                        }
                    }
                    new_children.push(updated);
                }
            }
            if !found {
                return Some(layout.clone());
            }
            let mut result = layout.clone();
            let n = new_children.len();
            let ratio = 1.0 / f64::from(u32::try_from(n).unwrap_or(1));
            for child in &mut new_children {
                if let Some(obj) = child.as_object_mut() {
                    obj.insert("ratio".to_string(), serde_json::json!(ratio));
                }
            }
            result["children"] = serde_json::Value::Array(new_children);
            let ratios: Vec<serde_json::Value> = (0..n).map(|_| serde_json::json!(ratio)).collect();
            result["ratios"] = serde_json::json!(ratios);
            Some(result)
        }
        _ => Some(layout.clone()),
    }
}

/// Like `insert_pane_into_layout` but allows specifying `title` and `shell_type` for the new leaf.
#[must_use]
pub fn insert_pane_into_layout_with_info(
    layout: &serde_json::Value,
    target_pane_id: &str,
    direction: &str,
    new_pane_id: &str,
    title: &str,
    shell_type: &str,
) -> Option<serde_json::Value> {
    insert_pane_into_layout_inner(
        layout,
        target_pane_id,
        direction,
        new_pane_id,
        Some(title),
        Some(shell_type),
    )
}

fn insert_pane_into_layout_inner(
    layout: &serde_json::Value,
    target_pane_id: &str,
    direction: &str,
    new_pane_id: &str,
    title: Option<&str>,
    shell_type: Option<&str>,
) -> Option<serde_json::Value> {
    let node_type = layout.get("type")?.as_str()?;
    match node_type {
        "leaf" => {
            let pane_id = layout.get("paneId")?.as_str()?;
            if pane_id == target_pane_id {
                // Found the target — wrap in a new split node
                let mut new_leaf = serde_json::json!({
                    "type": "leaf",
                    "paneId": new_pane_id,
                    "title": title.unwrap_or("Terminal"),
                    "ratio": 1,
                    "zoomed": false,
                });
                if let Some(st) = shell_type {
                    new_leaf["shell_type"] = serde_json::json!(st);
                }
                let existing_leaf = layout.clone();
                let split_id = uuid::Uuid::new_v4().to_string();
                Some(serde_json::json!({
                    "type": "split",
                    "id": split_id,
                    "direction": direction,
                    "children": [existing_leaf, new_leaf],
                    "ratios": [0.5, 0.5],
                }))
            } else {
                Some(layout.clone())
            }
        }
        "split" => {
            let parent_dir = layout.get("direction")?.as_str()?;
            let parent_dir_axis = normalize_split_direction(parent_dir);
            let children = layout.get("children")?.as_array()?;
            let mut new_children: Vec<serde_json::Value> = Vec::new();
            let mut found = false;
            for child in children {
                if let Some(updated) = insert_pane_into_layout_inner(
                    child,
                    target_pane_id,
                    direction,
                    new_pane_id,
                    title,
                    shell_type,
                ) {
                    let changed = found || updated != *child;
                    if changed {
                        found = true;
                    }
                    // If the child became a split with the same direction, flatten it
                    // (insert its children as siblings instead of nesting)
                    if changed
                        && updated.get("type").and_then(|t| t.as_str()) == Some("split")
                        && updated
                            .get("direction")
                            .and_then(|d| d.as_str())
                            .map(normalize_split_direction)
                            == Some(parent_dir_axis)
                    {
                        if let Some(inner_children) =
                            updated.get("children").and_then(|c| c.as_array())
                        {
                            new_children.extend(inner_children.iter().cloned());
                            continue;
                        }
                    }
                    new_children.push(updated);
                }
            }
            if !found {
                return Some(layout.clone());
            }
            let mut result = layout.clone();
            // Redistribute ratios equally among all children after insertion
            let n = new_children.len();
            let ratio = 1.0 / f64::from(u32::try_from(n).unwrap_or(1));
            for child in &mut new_children {
                if let Some(obj) = child.as_object_mut() {
                    obj.insert("ratio".to_string(), serde_json::json!(ratio));
                }
            }
            result["children"] = serde_json::Value::Array(new_children);
            let ratios: Vec<serde_json::Value> = (0..n).map(|_| serde_json::json!(ratio)).collect();
            result["ratios"] = serde_json::json!(ratios);
            Some(result)
        }
        _ => Some(layout.clone()),
    }
}

pub fn first_leaf_id(node: &serde_json::Value) -> Option<String> {
    let node_type = node.get("type")?.as_str()?;
    match node_type {
        "leaf" => node.get("paneId")?.as_str().map(String::from),
        "split" => {
            let children = node.get("children")?.as_array()?;
            for child in children {
                if let Some(id) = first_leaf_id(child) {
                    return Some(id);
                }
            }
            None
        }
        _ => None,
    }
}

fn parse_title_cwd(title: &str, home: &Path) -> Option<PathBuf> {
    let at = title.rfind('@')?;
    let tail = title.get(at + 1..)?;
    let colon = tail.find(':')?;
    let path_part = tail.get(colon + 1..)?.trim();
    if path_part.is_empty() {
        return None;
    }
    let path = if let Some(rest) = path_part.strip_prefix("~/") {
        home.join(rest)
    } else if path_part == "~" {
        home.to_path_buf()
    } else if Path::new(path_part).is_absolute() {
        PathBuf::from(path_part)
    } else {
        home.join(path_part)
    };
    Some(path)
}

pub struct SyncClient {
    pub id: String,
    pub tx: mpsc::UnboundedSender<String>,
}

/// Recursively check if a JSON layout tree contains a leaf with the given `pane_id`.
fn layout_has_pane(layout: &serde_json::Value, pane_id: &str) -> bool {
    if let Some(pid) = layout.get("paneId").and_then(|v| v.as_str()) {
        if pid == pane_id {
            return true;
        }
    }
    if let Some(children) = layout.get("children").and_then(|v| v.as_array()) {
        for child in children {
            if layout_has_pane(child, pane_id) {
                return true;
            }
        }
    }
    false
}

/// SSH keyboard-interactive auth prompt
#[derive(Clone, Debug, serde::Serialize)]
pub struct SshAuthPrompt {
    pub prompt: String,
    pub echo: bool,
}

/// Pending SSH keyboard-interactive auth state
///
/// Channel flow:
/// - SSH handler → `prompts_tx` → `prompts_rx` → sync WS → frontend
/// - frontend → sync WS → `responses_tx` → `responses_rx` → SSH handler
pub struct PendingSshAuth {
    pub prompts_tx: mpsc::UnboundedSender<Vec<SshAuthPrompt>>,
    pub prompts_rx: tokio::sync::Mutex<mpsc::UnboundedReceiver<Vec<SshAuthPrompt>>>,
    pub responses_tx: mpsc::UnboundedSender<Vec<String>>,
    pub responses_rx: tokio::sync::Mutex<mpsc::UnboundedReceiver<Vec<String>>>,
}

pub struct SessionManager {
    pub sessions: DashMap<String, Arc<Session>>,
    pub sync_clients: Arc<Mutex<Vec<SyncClient>>>,
    pub active_pane_id: Arc<Mutex<Option<String>>>,
    pub tab_layouts: DashMap<String, serde_json::Value>,
    pub pending_ssh_auth: DashMap<String, PendingSshAuth>,
    pub tab_order: Mutex<Vec<String>>,
    pub event_bus: EventBus,
    notify_port: AtomicU16,
    /// Set once (via `register_notifier`) so any authoritative pane-removal site — including
    /// natural PTY/SSH exit, which never goes through `kill_and_remove` — can notify the
    /// attention ledger without threading a notifier handle through every call site.
    notifier: OnceLock<Arc<crate::notification::NotificationBroadcast>>,
}

#[derive(Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SyncMsg {
    TabList {
        tabs: Vec<TabInfo>,
        active_pane_id: Option<String>,
    },
    TabCreated {
        tab_id: String,
        pane_id: String,
        layout: Option<serde_json::Value>,
        cwd: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        connection_id: Option<String>,
    },
    TabClosed {
        pane_id: String,
    },
    TabActivated {
        pane_id: String,
    },
    LayoutUpdated {
        pane_id: String,
        layout: serde_json::Value,
        active_pane_id: String,
    },
    PluginChanged {
        plugin_id: String,
        change: String,
    },
    ProcessExited {
        plugin_id: String,
        pid: u32,
        exit_code: Option<i32>,
    },
    CommandFinished {
        pane_id: String,
        command: String,
        exit_code: i32,
        duration_ms: u64,
        stdout: String,
        method: String,
    },
    WorkspaceCreated {
        workspace: crate::workspace_mgmt::Workspace,
    },
    WorkspaceUpdated {
        workspace: crate::workspace_mgmt::Workspace,
    },
    WorkspaceDeleted {
        id: String,
    },
    WorkspaceActivated {
        id: Option<String>,
    },
    WorkspaceReordered {
        ids: Vec<String>,
    },
    WorkspaceList {
        workspaces: Vec<crate::workspace_mgmt::Workspace>,
        active_workspace_id: Option<String>,
    },
}

#[derive(Serialize, Clone)]
pub struct TabInfo {
    pub tab_id: String,
    pub pane_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layout: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_pane_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// The `SshProfile.id` if this tab is an SSH session created from a profile.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connection_id: Option<String>,
}

impl Default for SessionManager {
    fn default() -> Self {
        Self::new()
    }
}

impl SessionManager {
    #[must_use]
    pub fn new() -> Self {
        Self {
            sessions: DashMap::new(),
            sync_clients: Arc::new(Mutex::new(Vec::new())),
            active_pane_id: Arc::new(Mutex::new(None)),
            tab_layouts: DashMap::new(),
            tab_order: Mutex::new(Vec::new()),
            pending_ssh_auth: DashMap::new(),
            event_bus: EventBus::new(),
            notify_port: AtomicU16::new(0),
            notifier: OnceLock::new(),
        }
    }

    /// Notifies the attention ledger that `pane_id` was authoritatively removed, if a notifier
    /// has been registered (via `register_notifier`). No-op otherwise (e.g. in unit tests that
    /// construct a bare `SessionManager`).
    pub(crate) fn pane_closed_notify(&self, pane_id: &str) {
        if let Some(notifier) = self.notifier.get() {
            notifier.pane_closed(pane_id);
        }
    }

    #[must_use]
    pub fn notify_port(&self) -> u16 {
        self.notify_port.load(Ordering::Relaxed)
    }

    pub fn set_notify_port(&self, port: u16) {
        self.notify_port.store(port, Ordering::Relaxed);
    }

    /// Insert a tab layout and record its order position.
    pub fn insert_tab(&self, tab_id: String, value: serde_json::Value) {
        let mut order = self.tab_order.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        if !order.contains(&tab_id) {
            order.push(tab_id.clone());
        }
        drop(order);
        self.tab_layouts.insert(tab_id, value);
    }

    /// Remove a tab layout and its order entry.
    pub fn remove_tab(&self, tab_id: &str) {
        self.tab_layouts.remove(tab_id);
        let mut order = self.tab_order.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        order.retain(|id| id != tab_id);
    }

    /// Check if a `pane_id` belongs to any registered tab layout.
    /// Used to prevent creating fallback PTY sessions for SSH panes.
    pub fn is_pane_in_any_tab(&self, pane_id: &str) -> bool {
        for entry in &self.tab_layouts {
            if let Some(layout) = entry.value().get("layout") {
                if layout_has_pane(layout, pane_id) {
                    return true;
                }
            }
        }
        false
    }

    /// # Panics
    /// Panics if `SyncMsg` serialization fails (should be infallible).
    #[allow(clippy::expect_used)]
    pub fn broadcast_sync(&self, msg: &SyncMsg) {
        let json = serde_json::to_string(msg).expect("serialization is infallible");
        let mut clients =
            self.sync_clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|c| c.tx.send(json.clone()).is_ok());
    }

    /// Broadcast to all sync clients except the one with the given ID.
    ///
    /// # Panics
    /// Panics if `SyncMsg` serialization fails (should be infallible).
    #[allow(clippy::expect_used)]
    pub fn broadcast_sync_others(&self, msg: &SyncMsg, exclude_id: &str) {
        let json = serde_json::to_string(msg).expect("serialization is infallible");
        let mut clients =
            self.sync_clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients.retain(|c| {
            if c.id == exclude_id {
                true // keep in list but don't send
            } else {
                c.tx.send(json.clone()).is_ok()
            }
        });
    }

    pub fn add_sync_client(&self) -> (String, mpsc::UnboundedReceiver<String>) {
        let id = uuid::Uuid::new_v4().to_string();
        let (tx, rx) = mpsc::unbounded_channel();
        self.sync_clients
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .push(SyncClient { id: id.clone(), tx });
        (id, rx)
    }

    pub fn broadcast_plugin_changed(&self, plugin_id: String, change: String) {
        self.broadcast_sync(&SyncMsg::PluginChanged { plugin_id, change });
    }

    /// Remove a session from the `DashMap` and explicitly kill its child process.
    /// Returns true if the session existed.
    ///
    /// This is necessary because the PTY reader task holds an `Arc<Session>`,
    /// preventing `Drop` from firing when we only remove from the `DashMap`.
    /// By killing the child first, the reader's `read()` returns Err/Ok(0),
    /// causing it to exit and release its `Arc`.
    pub fn kill_and_remove(&self, pane_id: &str) -> bool {
        if let Some((_, session)) = self.sessions.remove(pane_id) {
            session.kill_child();
            // Drop the input channel sender so the writer task's recv() returns
            // None and the task exits, releasing its Arc<Session>.
            session.input_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner).take();
            self.pane_closed_notify(pane_id);
            true
        } else {
            false
        }
    }

    /// Remove a `pane_id` from all parent tab layouts. If removing it causes
    /// a split to have only one child, the split collapses into that child.
    /// Returns the list of tab IDs whose layouts became empty (i.e. the pane
    /// was the last leaf) so the caller can broadcast `TabClosed` for them.
    pub fn purge_pane_from_layouts(&self, pane_id: &str) -> Vec<String> {
        let mut updates: Vec<(String, serde_json::Value)> = Vec::new();
        let mut emptied_tabs: Vec<String> = Vec::new();

        for entry in &self.tab_layouts {
            let tab_pane_id = entry.key();
            if tab_pane_id == pane_id {
                continue;
            }
            let val = entry.value();
            let Some(layout) = val.get("layout") else { continue };
            match remove_pane_from_layout(layout, pane_id) {
                None => {
                    // The pane was the only leaf — tab is now empty
                    emptied_tabs.push(tab_pane_id.clone());
                }
                Some(new_layout) if new_layout != *layout => {
                    let active = val.get("active_pane_id").and_then(|v| v.as_str());
                    let new_leaf_ids = collect_leaf_pane_ids(&new_layout);
                    let active_pane_id =
                        active.filter(|id| new_leaf_ids.iter().any(|lid| lid == *id));
                    let mut new_val = serde_json::json!({ "layout": new_layout });
                    if let Some(a) = active_pane_id {
                        new_val["active_pane_id"] = serde_json::Value::String(a.to_string());
                    }
                    updates.push((tab_pane_id.clone(), new_val));
                }
                _ => {}
            }
        }

        for (key, val) in updates {
            self.insert_tab(key, val);
        }
        for tab_id in &emptied_tabs {
            self.remove_tab(tab_id);
        }
        emptied_tabs
    }

    pub fn tab_list(&self) -> (Vec<TabInfo>, Option<String>) {
        // Prune stale tab layouts whose terminal leaves no longer have PTY sessions.
        // Leaves with kind=plugin|files|web have no PTY and are exempt - a tab with
        // only non-terminal leaves is NOT stale.
        let stale: Vec<String> = {
            self.tab_layouts
                .iter()
                .filter_map(|e| {
                    let v = e.value();
                    let layout = v.get("layout")?;
                    let all_leaf_ids = collect_leaf_pane_ids(layout);
                    if all_leaf_ids.is_empty() {
                        return Some(e.key().clone());
                    }
                    // Only terminal leaves require a live PTY session.
                    let terminal_ids = collect_terminal_leaf_pane_ids(layout);
                    if terminal_ids.iter().any(|id| !self.sessions.contains_key(id)) {
                        return Some(e.key().clone());
                    }
                    None
                })
                .collect()
        };
        for key in &stale {
            self.tab_layouts.remove(key);
        }
        if !stale.is_empty() {
            let mut order =
                self.tab_order.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            order.retain(|id| !stale.contains(id));
        }

        let order = self.tab_order.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let order_index = |tab_id: &str| -> usize {
            order.iter().position(|id| id == tab_id).unwrap_or(usize::MAX)
        };

        let mut tabs: Vec<TabInfo> = self
            .tab_layouts
            .iter()
            .map(|e| {
                let tab_id = e.key().clone();
                let v = e.value();
                let layout = v.get("layout").cloned().map(ensure_leaf_kind);
                let pane_id =
                    layout.as_ref().and_then(first_leaf_id).unwrap_or_else(|| tab_id.clone());
                let active_pane_id =
                    v.get("active_pane_id").and_then(|v| v.as_str()).map(String::from);
                let cwd = self.sessions.get(&pane_id).and_then(|s| {
                    s.cwd_state.lock().ok().map(|state| state.cwd.to_string_lossy().to_string())
                });
                let connection_id = self
                    .sessions
                    .get(&pane_id)
                    .and_then(|s| s.ssh_params.as_ref().and_then(|p| p.profile_id.clone()));
                TabInfo { tab_id, pane_id, layout, active_pane_id, cwd, connection_id }
            })
            .collect();

        tabs.sort_by_key(|t| order_index(&t.tab_id));
        drop(order);

        let active =
            self.active_pane_id.lock().unwrap_or_else(std::sync::PoisonError::into_inner).clone();
        (tabs, active)
    }

    /// When a PTY exits, find the parent tab and either remove it (single-pane)
    /// or update the layout (multi-pane). Returns the tab-level `pane_id` for
    /// single-pane tabs so the caller can broadcast `TabClosed`.
    pub fn on_pty_exited(&self, leaf_pane_id: &str) -> Option<String> {
        // Find the tab layout that contains this leaf
        let mut found_tab_id: Option<String> = None;
        for entry in &self.tab_layouts {
            let tab_id = entry.key();
            let val = entry.value();
            if let Some(layout) = val.get("layout") {
                let leaf_ids = collect_leaf_pane_ids(layout);
                if leaf_ids.iter().any(|id| id == leaf_pane_id) {
                    found_tab_id = Some(tab_id.clone());
                    break;
                }
            }
        }

        let tab_id = found_tab_id?;

        // Get the current layout for this tab
        let tab_val = self.tab_layouts.get(&tab_id)?;
        let layout = tab_val.value().get("layout")?.clone();
        let leaf_ids = collect_leaf_pane_ids(&layout);

        if leaf_ids.len() <= 1 {
            // Single-pane tab — remove the whole tab
            drop(tab_val);
            self.remove_tab(&tab_id);
            Some(tab_id)
        } else {
            // Multi-pane tab — update the layout by removing the exited pane
            let new_layout = remove_pane_from_layout(&layout, leaf_pane_id)?;
            let new_leaf_ids = collect_leaf_pane_ids(&new_layout);
            let active = tab_val.value().get("active_pane_id").and_then(|v| v.as_str());
            let active_pane_id = active
                .filter(|id| new_leaf_ids.iter().any(|lid| lid == *id))
                .or_else(|| new_leaf_ids.first().map(std::string::String::as_str))
                .unwrap_or("")
                .to_string();
            drop(tab_val);

            self.insert_tab(
                tab_id.clone(),
                serde_json::json!({
                    "layout": new_layout.clone(),
                    "active_pane_id": active_pane_id,
                }),
            );
            self.broadcast_sync(&SyncMsg::LayoutUpdated {
                pane_id: tab_id,
                layout: new_layout,
                active_pane_id,
            });
            None
        }
    }

    /// Registers the notifier once, so `kill_and_remove` and natural PTY/SSH exit paths can
    /// notify the attention ledger directly via `pane_closed_notify` without threading a
    /// notifier handle through every call site. Safe to call before `start_cleanup_task` (the
    /// two are independent — a bind failure or startup ordering issue must never suppress the
    /// detached-session reaper).
    pub fn register_notifier(&self, notifier: Arc<crate::notification::NotificationBroadcast>) {
        let _ = self.notifier.set(notifier);
    }

    pub fn start_cleanup_task(self: &Arc<Self>) {
        let manager = Arc::clone(self);
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
            let reap_secs = parse_reap_secs(std::env::var("DINOTTY_DETACH_REAP_SECS").ok());
            let timeout = std::time::Duration::from_secs(reap_secs);
            loop {
                interval.tick().await;
                // Two-pass: collect stale IDs first, then kill_and_remove.
                // Can't use retain() because we need to kill child processes.
                let stale: Vec<String> = manager
                    .sessions
                    .iter()
                    .filter_map(|entry| {
                        let status = entry
                            .value()
                            .status
                            .lock()
                            .unwrap_or_else(std::sync::PoisonError::into_inner);
                        match *status {
                            SessionStatus::Detached { since } if since.elapsed() >= timeout => {
                                Some(entry.key().clone())
                            }
                            _ => None,
                        }
                    })
                    .collect();
                for pane_id in stale {
                    // Re-check status before killing — the session may have been
                    // reconnected between the collect pass and now.
                    let should_kill = manager.sessions.get(&pane_id).is_some_and(|entry| {
                        let status = entry.value().status.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
                        matches!(*status, SessionStatus::Detached { since } if since.elapsed() >= timeout)
                    });

                    if should_kill {
                        info!("Cleanup: removing detached session: pane={}", pane_id);
                        // kill_and_remove now notifies the attention ledger internally.
                        manager.kill_and_remove(&pane_id);
                    }
                }
            }
        });
    }
}

#[cfg(test)]
mod tests;

/// Session regressions that use a stub with `SessionBackend::Exited` to avoid
/// spawning a real PTY/child process.
#[cfg(test)]
mod session_stub_tests {
    use super::*;
    use crate::notification::NotificationBroadcast;
    use std::sync::atomic::AtomicU64;
    use std::sync::mpsc as std_mpsc;
    use std::time::Duration;

    fn stub_session() -> Arc<Session> {
        let (resize_tx, _resize_rx) = watch::channel(None);
        let (output_tx, output_rx) = mpsc::unbounded_channel();
        Arc::new(Session {
            backend: tokio::sync::Mutex::new(SessionBackend::Exited),
            ssh_params: None,
            screen: Mutex::new(VirtualScreen::new(80, 24)),
            clients: Mutex::new(Vec::new()),
            next_client_id: AtomicU64::new(1),
            tauri_client_id: Mutex::new(None),
            input_tx: Mutex::new(None),
            status: Mutex::new(SessionStatus::Connected),
            size: Mutex::new((80, 24)),
            exited: Mutex::new(false),
            shell_type: "test".to_string(),
            tauri_on_exit: Mutex::new(None),
            cwd_state: Mutex::new(CwdState { cwd: PathBuf::from("/"), sniff_buf: Vec::new() }),
            sync: Mutex::new(SyncState::default()),
            sync_disable_hook: Mutex::new(None),
            resize_tx,
            ssh_cmd_tx: Mutex::new(None),
            ssh_handle: tokio::sync::Mutex::new(None),
            sftp_session: Mutex::new(None),
            remote_home: Mutex::new(None),
            remote_user: Mutex::new(None),
            output_tx,
            output_rx: Mutex::new(Some(output_rx)),
            pending_results: Mutex::new(Vec::new()),
        })
    }

    fn add_ready_client(session: &Session) -> mpsc::Receiver<SessionClientEvent> {
        let (client_id, rx) = session.add_client();
        let clients = session.clients.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        clients
            .iter()
            .find(|client| client.id == client_id)
            .expect("newly added client must exist")
            .snapshot_pending
            .store(false, Ordering::Relaxed);
        rx
    }

    fn assert_output(event: SessionClientEvent, expected: &str) {
        match event {
            SessionClientEvent::Output(output) => assert_eq!(output, expected),
            _ => panic!("expected Output event"),
        }
    }

    #[test]
    fn sync_wire_order_is_begin_buffer_end_live() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);

        session.set_sync_mode(true);
        session.broadcast("BUF");
        session.set_sync_mode(false);
        session.broadcast("LIVE");

        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncBegin)));
        assert_output(rx.try_recv().expect("buffered output"), "BUF");
        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncEnd)));
        assert_output(rx.try_recv().expect("live output"), "LIVE");
        assert!(matches!(rx.try_recv(), Err(mpsc::error::TryRecvError::Empty)));
    }

    #[test]
    fn sync_teardown_blocks_concurrent_broadcast_until_after_sync_end() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);
        session.set_sync_mode(true);
        session.broadcast("BUF");

        let weak_session = Arc::downgrade(&session);
        let (started_tx, started_rx) = std_mpsc::channel();
        let (finished_tx, finished_rx) = std_mpsc::channel();
        let thread_handle = Arc::new(Mutex::new(None));
        let hook_thread_handle = Arc::clone(&thread_handle);
        *session.sync_disable_hook.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
            Some(Box::new(move || {
                let broadcast_session = weak_session.upgrade().expect("session remains alive");
                let handle = std::thread::spawn(move || {
                    started_tx.send(()).expect("teardown hook remains alive");
                    broadcast_session.broadcast("LIVE");
                    let _ = finished_tx.send(());
                });
                *hook_thread_handle.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
                    Some(handle);

                started_rx
                    .recv_timeout(Duration::from_secs(1))
                    .expect("concurrent broadcaster must start");
                assert!(
                    matches!(
                        finished_rx.recv_timeout(Duration::from_millis(100)),
                        Err(std_mpsc::RecvTimeoutError::Timeout)
                    ),
                    "concurrent broadcast passed the sync guard before teardown completed"
                );
            }));

        session.set_sync_mode(false);
        thread_handle
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .take()
            .expect("hook spawned broadcaster")
            .join()
            .expect("concurrent broadcaster completed");

        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncBegin)));
        assert_output(rx.try_recv().expect("buffered output"), "BUF");
        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncEnd)));
        assert_output(rx.try_recv().expect("live output"), "LIVE");
        assert!(matches!(rx.try_recv(), Err(mpsc::error::TryRecvError::Empty)));
    }

    #[test]
    fn double_sync_disable_emits_exactly_one_sync_end() {
        let session = stub_session();
        let mut rx = add_ready_client(&session);

        session.set_sync_mode(true);
        session.set_sync_mode(false);
        session.set_sync_mode(false);

        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncBegin)));
        assert!(matches!(rx.try_recv(), Ok(SessionClientEvent::SyncEnd)));
        assert!(matches!(rx.try_recv(), Err(mpsc::error::TryRecvError::Empty)));
    }

    #[tokio::test]
    async fn kill_and_remove_notifies_attention_ledger_with_a_single_removal_delta() {
        let notifier = Arc::new(NotificationBroadcast::new());
        let manager = Arc::new(SessionManager::new());
        manager.register_notifier(Arc::clone(&notifier));

        let pane_id = "stub-pane";
        manager.sessions.insert(pane_id.to_string(), stub_session());
        notifier.broadcast_test_delta(pane_id, crate::notification::now_ms());
        let registration = notifier.register_client();
        notifier.take_data(registration.conn_id).unwrap(); // snapshot

        assert!(manager.kill_and_remove(pane_id));

        let delta = match notifier.take_data(registration.conn_id) {
            Some(crate::notification::ServerEnvelope::StateDelta { delta }) => delta,
            other => panic!("expected exactly one removal delta, got {other:?}"),
        };
        assert!(delta.panes.iter().any(|p| p.pane_id == pane_id && p.removed == Some(true)));
        // Single hub notification: nothing further queued.
        assert!(notifier.take_data(registration.conn_id).is_none());
    }
}
