#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::too_many_lines,
    clippy::doc_markdown,
    clippy::items_after_statements,
    clippy::needless_pass_by_value
)]
use axum::{
    extract::{
        ws::{close_code, CloseFrame, Message, WebSocket},
        ConnectInfo, Query, State, WebSocketUpgrade,
    },
    http::StatusCode,
    response::IntoResponse,
    Json,
};
use futures_util::{SinkExt, StreamExt};
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;
use std::sync::{
    atomic::{AtomicU32, Ordering},
    Arc,
};

use tracing::{error, info, warn};

use crate::history::HistoryState;
use crate::notification::{
    MarkReadRequest, NotificationBroadcast, ServerEnvelope, CLOSE_UPGRADE_REQUIRED, DRAIN_STALL_MS,
    MIN_PROTOCOL_VERSION,
};
use crate::session::{SessionClientEvent, SessionManager, SessionStatus, SyncMsg};
use crate::settings::SettingsState;
use crate::workspace_mgmt::WorkspacesState;

#[derive(Deserialize)]
pub struct WsQuery {
    #[serde(rename = "paneId")]
    pane_id: Option<String>,
    argv: Option<String>,
}

#[derive(Deserialize)]
pub struct NotificationWsQuery {
    v: Option<String>,
}

#[derive(Deserialize, Serialize, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMsg {
    Input {
        data: String,
    },
    Resize {
        cols: u16,
        rows: u16,
    },
    /// Client → server: request a snapshot at the client's final fit size.
    /// Server replies with `ReplayBegin` → scrollback+snapshot chunks → `ReplayEnd`,
    /// and applies PTY resize to (cols, rows) atomically with the snapshot.
    /// Replaces the legacy behavior where the server pushed a snapshot at
    /// stale session.size immediately on connect, which the client's fit-
    /// ladder could interrupt mid-write and cause absolute-row addressing
    /// to clamp/wrap to wrong dimensions.
    SnapshotRequest {
        cols: u16,
        rows: u16,
    },
}

#[derive(Deserialize, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SyncClientMsg {
    ActivateTab {
        pane_id: String,
    },
    CreateTab {
        layout: serde_json::Value,
        #[serde(default)]
        tab_id: Option<String>,
        #[serde(default)]
        pane_id: Option<String>,
    },
    CloseTab {
        pane_id: String,
    },
    ClosePane {
        pane_id: String,
    },
    UpdateLayout {
        pane_id: String,
        layout: serde_json::Value,
        active_pane_id: String,
    },
    /// 前端返回 keyboard-interactive 认证响应
    SshAuthResponse {
        pane_id: String,
        responses: Vec<String>,
    },
}

#[derive(Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMsg<'a> {
    Output {
        data: &'a str,
    },
    Resize {
        cols: u16,
        rows: u16,
    },
    ShellInfo {
        shell_type: &'a str,
    },
    Reconnected {
        cols: u16,
        rows: u16,
    },
    /// DEC mode 2026 transaction boundary. `SyncBegin` precedes buffered Output
    /// accumulated during synchronized output mode; `SyncEnd` follows the
    /// flushed Output. Frontend uses these to batch the buffered Output into
    /// a single xterm write, reducing intermediate rAF repaints.
    SyncBegin,
    SyncEnd,
    /// Replay transaction boundary. `ReplayBegin` precedes scrollback+snapshot
    /// chunks generated by the server at the client's requested size (see
    /// `SnapshotRequest`); `ReplayEnd` follows them. Frontend diverts Output into
    /// the transaction buffer during replay (same mechanism as SyncBegin/End)
    /// so the snapshot is written to xterm as a single batch and the fit-
    /// ladder / `ResizeObserver` / peer-follow cannot interrupt mid-write.
    /// Cols/rows carry the dimensions the snapshot was encoded at — client
    /// compares to its current wrapper size and re-requests on mismatch.
    ReplayBegin {
        cols: u16,
        rows: u16,
    },
    ReplayEnd,
    SessionExit,
    /// SSH keyboard-interactive 认证提示
    SshAuthPrompt {
        pane_id: String,
        prompts: Vec<crate::session::SshAuthPrompt>,
    },
}

#[allow(clippy::unused_async)]
pub async fn ws_handler(
    ws: WebSocketUpgrade,
    Query(q): Query<WsQuery>,
    State(manager): State<Arc<SessionManager>>,
    State(history): State<HistoryState>,
    State(settings): State<SettingsState>,
    ConnectInfo(_addr): ConnectInfo<SocketAddr>,
    _headers: axum::http::HeaderMap,
) -> impl IntoResponse {
    // WebSocket connections only attach to panes already created through /api/tabs.
    // Reject argv explicitly so a reconnect can never silently turn into a spawn request.
    if q.argv.is_some() {
        return StatusCode::BAD_REQUEST.into_response();
    }
    // paneId must reference a tab created via /api/tabs (or the sync WS
    // CreateTab message); otherwise an authenticated client could spawn
    // unbounded orphan PTYs by connecting with random/empty paneIds. Cookie
    // session auth (auth_middleware) handles access control; this check
    // prevents resource exhaustion.
    let Some(pane_id) = q.pane_id else {
        return StatusCode::BAD_REQUEST.into_response();
    };
    if !manager.is_pane_in_any_tab(&pane_id) {
        return StatusCode::FORBIDDEN.into_response();
    }
    ws.on_upgrade(move |socket| handle_socket(socket, pane_id, manager, history, settings))
        .into_response()
}

#[allow(clippy::unused_async)]
pub async fn sync_handler(
    ws: WebSocketUpgrade,
    State((manager, workspaces, settings)): State<(
        Arc<SessionManager>,
        WorkspacesState,
        SettingsState,
    )>,
    ConnectInfo(addr): ConnectInfo<SocketAddr>,
    headers: axum::http::HeaderMap,
) -> impl IntoResponse {
    let s = settings.read().await;
    let allowed_origins = s.auth.allowed_origins.clone();
    let trusted_proxies = s.auth.trusted_proxies.clone();
    drop(s);
    let real_ip = crate::auth::real_client_ip(&headers, addr.ip(), &trusted_proxies);
    if !crate::auth::check_ws_origin(&headers, &allowed_origins, real_ip, &trusted_proxies) {
        return StatusCode::FORBIDDEN.into_response();
    }
    ws.on_upgrade(move |socket| handle_sync_socket(socket, manager, workspaces, settings))
        .into_response()
}

async fn handle_sync_socket(
    socket: WebSocket,
    manager: Arc<SessionManager>,
    workspaces: WorkspacesState,
    settings: SettingsState,
) {
    let (ws_tx, mut ws_rx) = socket.split();

    // Channel for all outbound WS messages
    let (ws_out_tx, mut ws_out_rx) = tokio::sync::mpsc::unbounded_channel::<Message>();

    // Writer task: reads from channel, writes to WebSocket sink
    let writer_task = tokio::spawn(async move {
        let mut ws_tx = ws_tx;
        while let Some(msg) = ws_out_rx.recv().await {
            if ws_tx.send(msg).await.is_err() {
                break;
            }
        }
    });

    // Ping sender task: keep connection alive through NAT/proxy
    // Tracks missed pongs — if 2 consecutive pings go unanswered (60s), close connection.
    let missed_pongs = Arc::new(AtomicU32::new(0));
    let ping_tx = ws_out_tx.clone();
    let pong_counter = Arc::clone(&missed_pongs);
    let ping_task = tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
        interval.tick().await; // skip first immediate tick
        loop {
            interval.tick().await;
            if ping_tx.send(Message::Ping(vec![])).is_err() {
                break;
            }
            if pong_counter.fetch_add(1, Ordering::Relaxed) >= 2 {
                let _ = ping_tx.send(Message::Close(None));
                break;
            }
        }
    });

    // Register as sync client BEFORE sending tab_list so we don't miss any
    // broadcasts that happen between tab_list and registration.
    let (client_id, mut rx) = manager.add_sync_client();

    // Send current tab list with active tab
    let (tabs, active_pane_id) = manager.tab_list();
    let tab_list = SyncMsg::TabList { tabs, active_pane_id };
    let msg = serde_json::to_string(&tab_list).expect("serialization is infallible");
    if ws_out_tx.send(Message::Text(msg)).is_err() {
        return;
    }

    // Send current workspace list with active workspace
    {
        let ws = workspaces.read().await;
        let active_workspace_id = settings.read().await.active_workspace_id.clone();
        let workspace_list = SyncMsg::WorkspaceList { workspaces: ws.clone(), active_workspace_id };
        let msg = serde_json::to_string(&workspace_list).expect("serialization is infallible");
        let _ = ws_out_tx.send(Message::Text(msg));
    }

    // Use mpsc channel to bridge broadcast messages and direct responses to the WebSocket
    let (msg_tx, mut msg_rx) = tokio::sync::mpsc::unbounded_channel::<String>();

    // Forward broadcast messages into the shared channel
    let msg_tx_broadcast = msg_tx.clone();
    tokio::spawn(async move {
        while let Some(data) = rx.recv().await {
            if msg_tx_broadcast.send(data).is_err() {
                break;
            }
        }
    });

    // Forward all messages from the shared channel to the WebSocket
    let fwd_ws_out_tx = ws_out_tx.clone();
    let fwd = tokio::spawn(async move {
        while let Some(data) = msg_rx.recv().await {
            if fwd_ws_out_tx.send(Message::Text(data)).is_err() {
                break;
            }
        }
    });

    // Monitor SSH keyboard-interactive auth prompts and forward to frontend
    let auth_mgr = Arc::clone(&manager);
    let auth_ws_out = ws_out_tx.clone();
    tokio::spawn(async move {
        let mut known_keys: std::collections::HashSet<String> = std::collections::HashSet::new();
        loop {
            tokio::time::sleep(std::time::Duration::from_millis(100)).await;
            let current_keys: std::collections::HashSet<String> =
                auth_mgr.pending_ssh_auth.iter().map(|r| r.key().clone()).collect();
            for key in &current_keys {
                if !known_keys.contains(key) {
                    known_keys.insert(key.clone());
                    let mgr = Arc::clone(&auth_mgr);
                    let ws_out = auth_ws_out.clone();
                    let pane_id = key.clone();
                    tokio::spawn(async move {
                        loop {
                            tokio::time::sleep(std::time::Duration::from_millis(50)).await;
                            if !mgr.pending_ssh_auth.contains_key(&pane_id) {
                                break;
                            }
                            let prompt_data = {
                                let Some(auth) = mgr.pending_ssh_auth.get(&pane_id) else {
                                    break;
                                };
                                let mut rx = auth.prompts_rx.lock().await;
                                match rx.try_recv() {
                                    Ok(data) => Some(data),
                                    Err(tokio::sync::mpsc::error::TryRecvError::Empty) => None,
                                    Err(tokio::sync::mpsc::error::TryRecvError::Disconnected) => {
                                        break
                                    }
                                }
                            };
                            if let Some(prompts) = prompt_data {
                                let msg = serde_json::json!({
                                    "type": "ssh_auth_prompt",
                                    "pane_id": pane_id,
                                    "prompts": prompts,
                                });
                                if ws_out.send(Message::Text(msg.to_string())).is_err() {
                                    break;
                                }
                            }
                        }
                    });
                }
            }
            known_keys.retain(|k| current_keys.contains(k));
        }
    });

    // Process incoming sync messages from this client
    while let Some(Ok(msg)) = ws_rx.next().await {
        match msg {
            Message::Text(text) => {
                if let Ok(sync_msg) = serde_json::from_str::<SyncClientMsg>(&text) {
                    match sync_msg {
                        SyncClientMsg::ActivateTab { pane_id } => {
                            // Resolve leaf pane ID: pane_id may be a tab ID;
                            // look up the tab's stored active_pane_id for the actual leaf.
                            let leaf_id = manager
                                .tab_layouts
                                .get(&pane_id)
                                .and_then(|v| {
                                    v.get("active_pane_id")
                                        .and_then(|a| a.as_str())
                                        .map(String::from)
                                })
                                .unwrap_or(pane_id.clone());
                            *manager
                                .active_pane_id
                                .lock()
                                .unwrap_or_else(std::sync::PoisonError::into_inner) = Some(leaf_id);
                            manager.broadcast_sync_others(
                                &SyncMsg::TabActivated { pane_id },
                                &client_id,
                            );
                        }
                        SyncClientMsg::CreateTab { layout, tab_id, pane_id } => {
                            let tab_id = tab_id.unwrap_or_else(|| uuid::Uuid::new_v4().to_string());
                            let leaf_id = pane_id
                                .or_else(|| crate::session::first_leaf_id(&layout))
                                .unwrap_or_else(|| tab_id.clone());
                            *manager
                                .active_pane_id
                                .lock()
                                .unwrap_or_else(std::sync::PoisonError::into_inner) =
                                Some(leaf_id.clone());
                            manager.insert_tab(
                                tab_id.clone(),
                                serde_json::json!({
                                    "layout": layout,
                                    "active_pane_id": leaf_id,
                                }),
                            );
                            // Reply to the sender with server-generated IDs
                            let _ = msg_tx.send(
                                serde_json::to_string(&SyncMsg::TabCreated {
                                    tab_id: tab_id.clone(),
                                    pane_id: leaf_id.clone(),
                                    layout: Some(layout.clone()),
                                    cwd: None,
                                    connection_id: None,
                                })
                                .unwrap(),
                            );
                            // Broadcast to other clients
                            manager.broadcast_sync_others(
                                &SyncMsg::TabCreated {
                                    tab_id,
                                    pane_id: leaf_id,
                                    layout: Some(layout),
                                    cwd: None,
                                    connection_id: None,
                                },
                                &client_id,
                            );
                        }
                        SyncClientMsg::CloseTab { pane_id } => {
                            // Collect leaf pane IDs from the layout before removing it
                            let leaf_ids: Vec<String> = manager
                                .tab_layouts
                                .get(&pane_id)
                                .and_then(|v| v.get("layout").cloned())
                                .map(|layout| crate::session::collect_leaf_pane_ids(&layout))
                                .unwrap_or_default();
                            // Kill and remove PTY sessions for all leaves in this tab
                            // (kill_and_remove notifies the attention ledger internally).
                            for leaf_id in &leaf_ids {
                                manager.kill_and_remove(leaf_id);
                            }
                            manager.remove_tab(&pane_id);
                            // Remove stale pane_id from any parent tab layouts
                            manager.purge_pane_from_layouts(&pane_id);
                            manager
                                .broadcast_sync_others(&SyncMsg::TabClosed { pane_id }, &client_id);
                        }
                        SyncClientMsg::ClosePane { pane_id } => {
                            // kill_and_remove notifies the attention ledger internally.
                            manager.kill_and_remove(&pane_id);
                            // Collect affected layouts before purging
                            let before_layouts: Vec<(String, serde_json::Value)> = manager
                                .tab_layouts
                                .iter()
                                .map(|e| (e.key().clone(), e.value().clone()))
                                .collect();
                            let emptied_tabs = manager.purge_pane_from_layouts(&pane_id);
                            // Broadcast layout changes to other clients
                            for (tab_id, old_val) in &before_layouts {
                                if let Some(new_val) = manager.tab_layouts.get(tab_id) {
                                    if *new_val.value() != *old_val {
                                        let layout = new_val
                                            .value()
                                            .get("layout")
                                            .cloned()
                                            .unwrap_or(serde_json::Value::Null);
                                        let active = new_val
                                            .value()
                                            .get("active_pane_id")
                                            .and_then(|v| v.as_str())
                                            .unwrap_or("")
                                            .to_string();
                                        manager.broadcast_sync_others(
                                            &SyncMsg::LayoutUpdated {
                                                pane_id: tab_id.clone(),
                                                layout,
                                                active_pane_id: active,
                                            },
                                            &client_id,
                                        );
                                    }
                                }
                            }
                            // Broadcast TabClosed for tabs that became empty
                            for tab_id in emptied_tabs {
                                manager.broadcast_sync_others(
                                    &SyncMsg::TabClosed { pane_id: tab_id },
                                    &client_id,
                                );
                            }
                        }
                        SyncClientMsg::UpdateLayout { pane_id, layout, active_pane_id } => {
                            manager.insert_tab(
                                pane_id.clone(),
                                serde_json::json!({
                                    "layout": layout,
                                    "active_pane_id": active_pane_id,
                                }),
                            );
                            // Sync global active pane (same rationale as REST update_layout)
                            *manager
                                .active_pane_id
                                .lock()
                                .unwrap_or_else(std::sync::PoisonError::into_inner) =
                                Some(active_pane_id.clone());
                            manager.broadcast_sync_others(
                                &SyncMsg::LayoutUpdated { pane_id, layout, active_pane_id },
                                &client_id,
                            );
                        }
                        SyncClientMsg::SshAuthResponse { pane_id, responses } => {
                            // 将用户输入的 responses 转发给 SSH handler
                            if let Some(auth) = manager.pending_ssh_auth.get(&pane_id) {
                                let _ = auth.responses_tx.send(responses);
                            }
                        }
                    }
                }
            }
            Message::Ping(data) => {
                let _ = ws_out_tx.send(Message::Pong(data));
            }
            Message::Pong(_) => {
                missed_pongs.store(0, Ordering::Relaxed);
            }
            Message::Close(_) => break,
            Message::Binary(_) => {}
        }
    }
    fwd.abort();
    writer_task.abort();
    ping_task.abort();
}

async fn handle_socket(
    socket: WebSocket,
    pane_id: String,
    manager: Arc<SessionManager>,
    history: HistoryState,
    settings: SettingsState,
) {
    info!("WebSocket connected: pane={}", pane_id);
    let (ws_tx, mut ws_rx) = socket.split();
    let mut input_buffer = String::new();

    // Channel for all outbound WS messages (PTY output, Ping, Pong)
    let (ws_out_tx, mut ws_out_rx) = tokio::sync::mpsc::unbounded_channel::<Message>();

    // Writer task: reads from channel, writes to WebSocket sink
    let writer_task = tokio::spawn(async move {
        let mut ws_tx = ws_tx;
        while let Some(msg) = ws_out_rx.recv().await {
            if ws_tx.send(msg).await.is_err() {
                break;
            }
        }
    });

    // Ping sender task: keep connection alive through NAT/proxy
    // Tracks missed pongs — if 2 consecutive pings go unanswered (60s), close connection.
    let missed_pongs = Arc::new(AtomicU32::new(0));
    let ping_tx = ws_out_tx.clone();
    let pong_counter = Arc::clone(&missed_pongs);
    let ping_task = tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
        interval.tick().await; // skip first immediate tick
        loop {
            interval.tick().await;
            if ping_tx.send(Message::Ping(vec![])).is_err() {
                break;
            }
            if pong_counter.fetch_add(1, Ordering::Relaxed) >= 2 {
                let _ = ping_tx.send(Message::Close(None));
                break;
            }
        }
    });

    // Check if session already exists (reconnection / multi-client case)
    let existing_session = manager.sessions.get(&pane_id).map(|r| Arc::clone(r.value()));
    if let Some(session) = existing_session {
        info!("Joining existing session: pane={}", pane_id);

        *session.status.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
            SessionStatus::Connected;

        // Fit-then-snapshot handshake (proposal 3): send Reconnected with the
        // current session.size as info only — do NOT push scrollback/snapshot
        // yet. The client converges its local layout, fits once, and replies
        // with SnapshotRequest{cols, rows}; the server then resizes PTY+screen
        // to the client's final size atomically with the snapshot, and replies
        // with ReplayBegin → chunks → ReplayEnd. add_client sets
        // snapshot_pending=true so broadcast() drops live Output for this
        // client until ReplayEnd is enqueued (effect captured by snapshot).
        let (cols, rows, client_id, mut rx) = {
            let (cols, rows) =
                *session.size.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            let (client_id, rx) = session.add_client();
            info!(
                "Reconnected (snapshot pending) pane={}: info_cols={}, info_rows={}",
                pane_id, cols, rows
            );
            (cols, rows, client_id, rx)
        };

        // Send reconnected message — client should reset xterm, converge
        // layout, fit once, then send SnapshotRequest{cols, rows}.
        let msg = serde_json::to_string(&ServerMsg::Reconnected { cols, rows })
            .expect("serialization is infallible");
        info!("Sending reconnected to pane={}: {}", pane_id, msg);
        if ws_out_tx.send(Message::Text(msg)).is_err() {
            error!("Failed to send reconnected msg to pane={}", pane_id);
            return;
        }
        info!("Reconnected sent (snapshot pending SnapshotRequest), pane={}", pane_id);

        let fwd_ws_out_tx = ws_out_tx.clone();
        let fwd_pane = pane_id.clone();
        let fwd = tokio::spawn(async move {
            while let Some(event) = rx.recv().await {
                let msg = match event {
                    SessionClientEvent::Output(data) => {
                        serde_json::to_string(&ServerMsg::Output { data: &data })
                    }
                    SessionClientEvent::Resize { cols, rows } => {
                        serde_json::to_string(&ServerMsg::Resize { cols, rows })
                    }
                    SessionClientEvent::SessionExit { pane_id: _ } => {
                        serde_json::to_string(&ServerMsg::SessionExit)
                    }
                    SessionClientEvent::SyncBegin => serde_json::to_string(&ServerMsg::SyncBegin),
                    SessionClientEvent::SyncEnd => serde_json::to_string(&ServerMsg::SyncEnd),
                    SessionClientEvent::ReplayBegin { cols, rows } => {
                        serde_json::to_string(&ServerMsg::ReplayBegin { cols, rows })
                    }
                    SessionClientEvent::ReplayEnd => serde_json::to_string(&ServerMsg::ReplayEnd),
                }
                .expect("serialization is infallible");
                if fwd_ws_out_tx.send(Message::Text(msg)).is_err() {
                    info!("WS forwarder (reconnect): send failed, exiting pane={}", fwd_pane);
                    break;
                }
            }
            info!("WS forwarder (reconnect): channel closed, exiting pane={}", fwd_pane);
        });

        // Input channel: replaces old channel so only this connection writes to PTY
        let mut input_rx = session.replace_input_channel();
        let write_session = Arc::clone(&session);
        let write_pane = pane_id.clone();
        let is_ssh = write_session.is_ssh();
        tokio::spawn(async move {
            while let Some(first) = input_rx.recv().await {
                if write_session.is_exited() {
                    break;
                }
                // Batch: drain all pending messages to minimize lock acquisitions
                let mut batch = first;
                while let Ok(data) = input_rx.try_recv() {
                    batch.push_str(&data);
                }
                let batch_len = batch.len();
                let result = if is_ssh {
                    write_session.write_input_async(batch.as_bytes()).await
                } else {
                    let ws = Arc::clone(&write_session);
                    tokio::task::spawn_blocking(move || ws.write_input_blocking(batch.as_bytes()))
                        .await
                        .unwrap_or_else(|e| Err(e.to_string()))
                };
                match result {
                    Ok(()) => {}
                    Err(e) => {
                        error!("PTY write error ({}B): {}, pane={}", batch_len, e, write_pane);
                        break;
                    }
                }
            }
            info!("PTY write task (reconnect) exited, pane={}", write_pane);
        });

        // Read loop
        while let Some(Ok(msg)) = ws_rx.next().await {
            match msg {
                Message::Text(text) => match serde_json::from_str::<ClientMsg>(&text) {
                    Ok(ClientMsg::Input { data }) => {
                        for ch in data.chars() {
                            if ch == '\r' || ch == '\n' {
                                let cmd = input_buffer.trim().to_string();
                                if !cmd.is_empty() {
                                    let h = history.clone();
                                    tokio::spawn(async move {
                                        h.push_realtime(&cmd).await;
                                    });
                                }
                                input_buffer.clear();
                            } else if ch == '\x7f' || ch == '\x08' {
                                input_buffer.pop();
                            } else if ch == '\x03' || ch == '\x15' {
                                input_buffer.clear();
                            } else if !ch.is_control() {
                                input_buffer.push(ch);
                            }
                        }
                        let tx = session
                            .input_tx
                            .lock()
                            .unwrap_or_else(std::sync::PoisonError::into_inner);
                        if let Some(tx) = tx.as_ref() {
                            let _ = tx.send(data);
                        }
                    }
                    Ok(ClientMsg::Resize { cols, rows }) => {
                        session.resize_debounced(client_id, cols, rows);
                    }
                    Ok(ClientMsg::SnapshotRequest { cols, rows }) => {
                        if let Err(e) = session
                            .atomic_resize_and_snapshot_for_client(client_id, cols, rows)
                            .await
                        {
                            warn!("snapshot_request failed: {e}, pane={}", pane_id);
                        }
                    }
                    Err(e) => error!("parse msg: {}", e),
                },
                Message::Ping(data) => {
                    let _ = ws_out_tx.send(Message::Pong(data));
                }
                Message::Pong(_) => {
                    missed_pongs.store(0, Ordering::Relaxed);
                }
                Message::Close(_) => break,
                Message::Binary(_) => {}
            }
        }

        fwd.abort();
        writer_task.abort();
        ping_task.abort();
        session.remove_client(client_id);

        if !session.has_clients() {
            *session.status.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
                SessionStatus::Detached { since: std::time::Instant::now() };
            info!("Session detached (all clients gone): pane={}", pane_id);
        }
        return;
    }

    // ── New session ──
    // If the pane belongs to a registered tab (e.g. SSH) but the session is gone,
    // the session must have exited. Don't silently create a local PTY.
    if manager.is_pane_in_any_tab(&pane_id) {
        info!("Pane {} belongs to a tab but session is gone — sending session_exit", pane_id);
        let msg =
            serde_json::to_string(&ServerMsg::SessionExit).expect("serialization is infallible");
        let _ = ws_out_tx.send(Message::Text(msg));
        // Keep the connection alive briefly so the client receives the message
        if let Some(Ok(_)) = ws_rx.next().await {}
        return;
    }

    info!("No existing session found for pane={}, creating new PTY session", pane_id);
    let cwd = settings.read().await.resolved_default_workspace_root();
    let (session, shell_type) =
        match crate::pty::create_session(&manager, &pane_id, None, None, cwd, None) {
            Ok(x) => x,
            Err(e) => {
                error!("{}", e);
                return;
            }
        };

    let (client_id, mut rx) = session.add_client();

    // Send shell info
    let shell_info = serde_json::to_string(&ServerMsg::ShellInfo { shell_type: &shell_type })
        .expect("serialization is infallible");
    let _ = ws_out_tx.send(Message::Text(shell_info));

    // Forward PTY output to this WS client
    let fwd_ws_out_tx = ws_out_tx.clone();
    let fwd_pane = pane_id.clone();
    let fwd = tokio::spawn(async move {
        while let Some(event) = rx.recv().await {
            let msg = match event {
                SessionClientEvent::Output(data) => {
                    serde_json::to_string(&ServerMsg::Output { data: &data })
                }
                SessionClientEvent::Resize { cols, rows } => {
                    serde_json::to_string(&ServerMsg::Resize { cols, rows })
                }
                SessionClientEvent::SessionExit { pane_id: _ } => {
                    serde_json::to_string(&ServerMsg::SessionExit)
                }
                SessionClientEvent::SyncBegin => serde_json::to_string(&ServerMsg::SyncBegin),
                SessionClientEvent::SyncEnd => serde_json::to_string(&ServerMsg::SyncEnd),
                SessionClientEvent::ReplayBegin { cols, rows } => {
                    serde_json::to_string(&ServerMsg::ReplayBegin { cols, rows })
                }
                SessionClientEvent::ReplayEnd => serde_json::to_string(&ServerMsg::ReplayEnd),
            }
            .expect("serialization is infallible");
            if fwd_ws_out_tx.send(Message::Text(msg)).is_err() {
                info!("WS forwarder: send failed, exiting pane={}", fwd_pane);
                break;
            }
        }
        info!("WS forwarder: channel closed, exiting pane={}", fwd_pane);
    });

    // Input channel: dedicated write task reads from channel → PTY writer
    let mut input_rx = session.replace_input_channel();
    let write_session = Arc::clone(&session);
    let write_pane = pane_id.clone();
    let is_ssh = write_session.is_ssh();
    tokio::spawn(async move {
        while let Some(first) = input_rx.recv().await {
            if write_session.is_exited() {
                break;
            }
            // Batch: drain all pending messages to minimize lock acquisitions
            let mut batch = first;
            while let Ok(data) = input_rx.try_recv() {
                batch.push_str(&data);
            }
            let batch_len = batch.len();
            let result = if is_ssh {
                write_session.write_input_async(batch.as_bytes()).await
            } else {
                let ws = Arc::clone(&write_session);
                tokio::task::spawn_blocking(move || ws.write_input_blocking(batch.as_bytes()))
                    .await
                    .unwrap_or_else(|e| Err(e.to_string()))
            };
            match result {
                Ok(()) => {}
                Err(e) => {
                    error!("PTY write error ({}B): {}, pane={}", batch_len, e, write_pane);
                    break;
                }
            }
        }
        info!("PTY write task exited, pane={}", write_pane);
    });

    // WS read loop
    while let Some(Ok(msg)) = ws_rx.next().await {
        match msg {
            Message::Text(text) => match serde_json::from_str::<ClientMsg>(&text) {
                Ok(ClientMsg::Input { data }) => {
                    for ch in data.chars() {
                        if ch == '\r' || ch == '\n' {
                            let cmd = input_buffer.trim().to_string();
                            if !cmd.is_empty() {
                                let h = history.clone();
                                tokio::spawn(async move {
                                    h.push_realtime(&cmd).await;
                                });
                            }
                            input_buffer.clear();
                        } else if ch == '\x7f' || ch == '\x08' {
                            input_buffer.pop();
                        } else if ch == '\x03' || ch == '\x15' {
                            input_buffer.clear();
                        } else if !ch.is_control() {
                            input_buffer.push(ch);
                        }
                    }
                    let tx =
                        session.input_tx.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
                    if let Some(tx) = tx.as_ref() {
                        let _ = tx.send(data);
                    }
                }
                Ok(ClientMsg::Resize { cols, rows }) => {
                    session.resize_debounced(client_id, cols, rows);
                }
                Ok(ClientMsg::SnapshotRequest { cols, rows }) => {
                    if let Err(e) =
                        session.atomic_resize_and_snapshot_for_client(client_id, cols, rows).await
                    {
                        warn!("snapshot_request failed: {e}, pane={}", pane_id);
                    }
                }
                Err(e) => error!("parse msg: {}", e),
            },
            Message::Ping(data) => {
                let _ = ws_out_tx.send(Message::Pong(data));
            }
            Message::Pong(_) => {
                missed_pongs.store(0, Ordering::Relaxed);
            }
            Message::Close(_) => break,
            Message::Binary(_) => {}
        }
    }

    fwd.abort();
    writer_task.abort();
    ping_task.abort();
    session.remove_client(client_id);

    if !session.has_clients() {
        *session.status.lock().unwrap_or_else(std::sync::PoisonError::into_inner) =
            SessionStatus::Detached { since: std::time::Instant::now() };
        info!("Session detached (all clients gone): pane={}", pane_id);
    }
}

#[allow(clippy::unused_async)]
pub async fn notification_ws_handler(
    ws: WebSocketUpgrade,
    Query(q): Query<NotificationWsQuery>,
    State(notifier): State<Arc<NotificationBroadcast>>,
    State(settings): State<SettingsState>,
    ConnectInfo(addr): ConnectInfo<SocketAddr>,
    headers: axum::http::HeaderMap,
) -> impl IntoResponse {
    let s = settings.read().await;
    let allowed_origins = s.auth.allowed_origins.clone();
    let trusted_proxies = s.auth.trusted_proxies.clone();
    drop(s);
    let real_ip = crate::auth::real_client_ip(&headers, addr.ip(), &trusted_proxies);
    if !crate::auth::check_ws_origin(&headers, &allowed_origins, real_ip, &trusted_proxies) {
        return StatusCode::FORBIDDEN.into_response();
    }
    let version = notification_protocol_version(q.v.as_deref());
    ws.on_upgrade(move |socket| handle_notification_socket(socket, notifier, version))
        .into_response()
}

pub(crate) fn notification_protocol_version(value: Option<&str>) -> u64 {
    value.and_then(|value| value.parse::<u64>().ok()).unwrap_or(0)
}

async fn handle_notification_socket(
    mut socket: WebSocket,
    notifier: Arc<NotificationBroadcast>,
    version: u64,
) {
    if version < MIN_PROTOCOL_VERSION {
        let _ = socket
            .send(Message::Close(Some(CloseFrame {
                code: CLOSE_UPGRADE_REQUIRED,
                reason: "protocol_upgrade_required".into(),
            })))
            .await;
        return;
    }

    let registration = notifier.register_client();
    let conn_id = registration.conn_id;
    let (ws_tx, mut ws_rx) = socket.split();
    let (pong_tx, mut pong_rx) = tokio::sync::mpsc::channel::<Vec<u8>>(8);
    let writer_notifier = Arc::clone(&notifier);
    let mut data_wake = registration.data_wake;
    let mut control = registration.control;
    let mut disconnect = registration.disconnect;
    let mut writer_task = tokio::spawn(async move {
        let mut ws_tx = ws_tx;
        // Send `message` with the drain-stall timeout. Returns `false` if the writer must stop
        // (send error/timeout, or the message itself was a Close frame).
        async fn send_one(
            ws_tx: &mut futures_util::stream::SplitSink<WebSocket, Message>,
            message: Message,
        ) -> bool {
            let closing = matches!(message, Message::Close(_));
            match tokio::time::timeout(
                std::time::Duration::from_millis(DRAIN_STALL_MS),
                ws_tx.send(message),
            )
            .await
            {
                Ok(Ok(())) => !closing,
                Ok(Err(_)) | Err(_) => false,
            }
        }

        let mut ping_interval = tokio::time::interval(std::time::Duration::from_secs(30));
        ping_interval.tick().await; // skip the immediate first tick

        'outer: loop {
            tokio::select! {
                biased;
                changed = disconnect.changed() => {
                    if changed.is_err() || *disconnect.borrow() {
                        let message = Message::Close(Some(CloseFrame {
                            code: close_code::RESTART,
                            reason: "notification client stalled; reconnect".into(),
                        }));
                        send_one(&mut ws_tx, message).await;
                        break 'outer;
                    }
                }
                envelope = control.recv() => {
                    let Some(envelope) = envelope else { break 'outer };
                    if !send_one(&mut ws_tx, envelope_message(envelope)).await {
                        break 'outer;
                    }
                }
                pong = pong_rx.recv() => {
                    let Some(data) = pong else { break 'outer };
                    if !send_one(&mut ws_tx, Message::Pong(data)).await {
                        break 'outer;
                    }
                }
                wake = data_wake.recv() => {
                    match wake {
                        Some(()) => {
                            // Drain the whole queue on one wake token — `take_data` returning
                            // `None` just means the queue is currently empty (NORMAL), never a
                            // reason to stop the writer.
                            while let Some(envelope) = writer_notifier.take_data(conn_id) {
                                if !send_one(&mut ws_tx, envelope_message(envelope)).await {
                                    break 'outer;
                                }
                            }
                        }
                        None => break 'outer, // wake channel closed: client unregistered
                    }
                }
                _ = ping_interval.tick() => {
                    if !send_one(&mut ws_tx, Message::Ping(vec![])).await {
                        break 'outer;
                    }
                }
            }
        }
    });

    loop {
        tokio::select! {
            msg = ws_rx.next() => {
                match msg {
                    Some(Ok(Message::Ping(data))) => {
                        if pong_tx.try_send(data).is_err() {
                            break;
                        }
                    }
                    Some(Ok(Message::Text(text))) => {
                        if let Some(request) = parse_mark_read(&text) {
                            notifier.apply_mark_read(conn_id, &request);
                        } else {
                            tracing::debug!("ignoring malformed notification WebSocket message");
                        }
                    }
                    Some(Ok(Message::Close(_)) | Err(_)) | None => break,
                    Some(Ok(_)) => {}
                }
            }
            _ = &mut writer_task => break,
        }
    }
    writer_task.abort();
    notifier.unregister_client(conn_id);
}

fn envelope_message(envelope: ServerEnvelope) -> Message {
    Message::Text(serde_json::to_string(&envelope).expect("serialization is infallible"))
}

fn parse_mark_read(text: &str) -> Option<MarkReadRequest> {
    let value: serde_json::Value = serde_json::from_str(text).ok()?;
    if value.get("type")?.as_str()? != "notification.mark_read" {
        return None;
    }
    let request: MarkReadRequest = serde_json::from_value(value).ok()?;
    if request.v < MIN_PROTOCOL_VERSION
        || request.epoch.is_empty()
        || request.client_id.is_empty()
        || request.request_id.is_empty()
        || request
            .panes
            .iter()
            .any(|pane| pane.pane_id.is_empty() || pane.through_event_seq.parse::<u64>().is_err())
        || request.notifs.iter().any(|notif| notif.notif_id.is_empty())
    {
        return None;
    }
    Some(request)
}

#[derive(Deserialize)]
pub struct InputRequest {
    pub pane_id: Option<String>,
    pub data: String,
}

/// # Panics
/// Panics if the internal mutex is poisoned.
pub async fn post_input(
    State((manager, settings)): State<(Arc<SessionManager>, SettingsState)>,
    Json(req): Json<InputRequest>,
) -> impl IntoResponse {
    let s = settings.read().await;
    if !s.open_api.enabled {
        return (
            StatusCode::FORBIDDEN,
            Json(serde_json::json!({ "error": "open_api is disabled" })),
        );
    }
    drop(s);

    let pane_id = req.pane_id.clone().or_else(|| {
        manager.active_pane_id.lock().unwrap_or_else(std::sync::PoisonError::into_inner).clone()
    });

    let pane_id = match pane_id {
        Some(id) if manager.sessions.contains_key(&id) => id,
        _ => {
            // Fall back to first available session
            match manager.sessions.iter().next() {
                Some(entry) => entry.key().clone(),
                None => {
                    return (
                        StatusCode::BAD_REQUEST,
                        Json(serde_json::json!({ "error": "no active pane" })),
                    )
                }
            }
        }
    };

    match manager.sessions.get(&pane_id) {
        Some(session) => {
            let _ = session.write_input_async(req.data.as_bytes()).await;
            (StatusCode::OK, Json(serde_json::json!({ "ok": true })))
        }
        None => (StatusCode::NOT_FOUND, Json(serde_json::json!({ "error": "pane not found" }))),
    }
}

/// # Panics
/// Panics if the internal mutex is poisoned.
pub async fn handle_open_api_ws(socket: WebSocket, manager: Arc<SessionManager>, pane_id: String) {
    let session = match manager.sessions.get(&pane_id) {
        Some(s) => Arc::clone(s.value()),
        None => return,
    };

    let (ws_tx, mut ws_rx) = socket.split();
    let (ws_out_tx, mut ws_out_rx) = tokio::sync::mpsc::unbounded_channel::<Message>();

    // Writer task
    let writer_task = tokio::spawn(async move {
        let mut ws_tx = ws_tx;
        while let Some(msg) = ws_out_rx.recv().await {
            if ws_tx.send(msg).await.is_err() {
                break;
            }
        }
    });

    // Ping task
    let ping_tx = ws_out_tx.clone();
    let ping_task = tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
        interval.tick().await;
        loop {
            interval.tick().await;
            if ping_tx.send(Message::Ping(vec![])).is_err() {
                break;
            }
        }
    });

    // Register as broadcast client
    let (client_id, mut rx) = session.add_client();

    // Forward broadcast output to WS
    let fwd_ws_out_tx = ws_out_tx.clone();
    let fwd_pane = pane_id.clone();
    let fwd = tokio::spawn(async move {
        while let Some(event) = rx.recv().await {
            let msg = match event {
                SessionClientEvent::Output(data) => {
                    serde_json::to_string(&ServerMsg::Output { data: &data })
                }
                SessionClientEvent::Resize { cols, rows } => {
                    serde_json::to_string(&ServerMsg::Resize { cols, rows })
                }
                SessionClientEvent::SessionExit { pane_id: _ } => {
                    serde_json::to_string(&ServerMsg::SessionExit)
                }
                SessionClientEvent::SyncBegin => serde_json::to_string(&ServerMsg::SyncBegin),
                SessionClientEvent::SyncEnd => serde_json::to_string(&ServerMsg::SyncEnd),
                SessionClientEvent::ReplayBegin { cols, rows } => {
                    serde_json::to_string(&ServerMsg::ReplayBegin { cols, rows })
                }
                SessionClientEvent::ReplayEnd => serde_json::to_string(&ServerMsg::ReplayEnd),
            }
            .expect("serialization is infallible");
            if fwd_ws_out_tx.send(Message::Text(msg)).is_err() {
                info!("WS forwarder (open_api): send failed, exiting pane={}", fwd_pane);
                break;
            }
        }
        info!("WS forwarder (open_api): channel closed, exiting pane={}", fwd_pane);
    });

    // PTY write task: avoids blocking the WS read loop with synchronous I/O
    let (pty_in_tx, mut pty_in_rx) = tokio::sync::mpsc::unbounded_channel::<String>();
    let write_session = Arc::clone(&session);
    let write_pane = pane_id.clone();
    let is_ssh = write_session.is_ssh();
    tokio::spawn(async move {
        while let Some(first) = pty_in_rx.recv().await {
            if write_session.is_exited() {
                break;
            }
            let mut batch = first;
            while let Ok(data) = pty_in_rx.try_recv() {
                batch.push_str(&data);
            }
            let batch_len = batch.len();
            let result = if is_ssh {
                write_session.write_input_async(batch.as_bytes()).await
            } else {
                let ws = Arc::clone(&write_session);
                tokio::task::spawn_blocking(move || ws.write_input_blocking(batch.as_bytes()))
                    .await
                    .unwrap_or_else(|e| Err(e.to_string()))
            };
            match result {
                Ok(()) => {}
                Err(e) => {
                    error!("PTY write error ({}B): {}, pane={}", batch_len, e, write_pane);
                    break;
                }
            }
        }
        info!("PTY write task (open_api) exited, pane={}", write_pane);
    });

    // Read loop: accept Input and Resize messages
    while let Some(Ok(msg)) = ws_rx.next().await {
        match msg {
            Message::Text(text) => {
                if let Ok(client_msg) = serde_json::from_str::<ClientMsg>(&text) {
                    match client_msg {
                        ClientMsg::Input { data } => {
                            let _ = pty_in_tx.send(data);
                        }
                        ClientMsg::Resize { cols, rows } => {
                            session.resize_debounced(client_id, cols, rows);
                        }
                        ClientMsg::SnapshotRequest { cols, rows } => {
                            if let Err(e) = session
                                .atomic_resize_and_snapshot_for_client(client_id, cols, rows)
                                .await
                            {
                                warn!("snapshot_request failed: {e}, pane={}", pane_id);
                            }
                        }
                    }
                }
            }
            Message::Ping(data) => {
                let _ = ws_out_tx.send(Message::Pong(data));
            }
            Message::Close(_) => break,
            _ => {}
        }
    }

    fwd.abort();
    writer_task.abort();
    ping_task.abort();
    session.remove_client(client_id);
}

#[cfg(test)]
mod tests;
