use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
pub struct WsQuery {
    #[serde(rename = "paneId")]
    pub pane_id: Option<String>,
    pub argv: Option<String>,
}

#[derive(Deserialize, Serialize, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMsg {
    Input {
        data: String,
    },
    Resize {
        cols: u16,
        rows: u16,
    },
    /// Client -> server: request a snapshot at the client's final fit size.
    /// Server replies with `ReplayBegin` -> scrollback+snapshot chunks -> `ReplayEnd`,
    /// and applies PTY resize to (cols, rows) atomically with the snapshot.
    /// Replaces the legacy behavior where the server pushed a snapshot at
    /// stale session.size immediately on connect, which the client's fit-
    /// ladder could interrupt mid-write and cause absolute-row addressing
    /// to clamp/wrap to wrong dimensions.
    SnapshotRequest {
        cols: u16,
        rows: u16,
    },
}

#[derive(Deserialize, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SyncClientMsg {
    ActivateTab {
        pane_id: String,
    },
    CreateTab {
        layout: serde_json::Value,
        #[serde(default)]
        tab_id: Option<String>,
        #[serde(default)]
        pane_id: Option<String>,
    },
    CloseTab {
        pane_id: String,
    },
    ClosePane {
        pane_id: String,
    },
    UpdateLayout {
        pane_id: String,
        layout: serde_json::Value,
        active_pane_id: String,
    },
    /// 前端返回 keyboard-interactive 认证响应
    SshAuthResponse {
        pane_id: String,
        responses: Vec<String>,
    },
    /// 前端标记通知已读（原 /ws/notify 的 notification.mark_read 上行，迁入 sync WS）
    MarkRead {
        #[serde(flatten)]
        request: crate::notification::MarkReadRequest,
    },
    RenameTab {
        tab_id: String,
        title: String,
    },
    /// Mission Control operation from a sync client (hardware keyboard or
    /// desktop frontend). Server holds the global MC state and broadcasts
    /// `MissionControlToggled` / `SelectionChanged` to all clients.
    MissionControlOp {
        op: crate::mission_control::McOp,
    },
    /// Terminal input from a sync client that has no `/ws/<paneId>` socket
    /// of its own (hardware keyboard). Routed to the active pane's PTY.
    /// Server-side safety net: if MC is open, Input is dropped to avoid the
    /// hardware keyboard leaking keystrokes into the terminal while the user
    /// is navigating the overview.
    Input {
        data: String,
    },
}

#[derive(Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMsg<'a> {
    Output {
        data: &'a str,
    },
    Resize {
        cols: u16,
        rows: u16,
    },
    ShellInfo {
        shell_type: &'a str,
    },
    SessionError {
        code: &'a str,
    },
    Reconnected {
        cols: u16,
        rows: u16,
    },
    /// DEC mode 2026 transaction boundary. `SyncBegin` precedes buffered Output
    /// accumulated during synchronized output mode; `SyncEnd` follows the
    /// flushed Output. Frontend uses these to batch the buffered Output into
    /// a single xterm write, reducing intermediate rAF repaints.
    SyncBegin,
    SyncEnd,
    /// Replay transaction boundary. `ReplayBegin` precedes scrollback+snapshot
    /// chunks generated by the server at the client's requested size (see
    /// `SnapshotRequest`); `ReplayEnd` follows them. Frontend diverts Output into
    /// the transaction buffer during replay (same mechanism as SyncBegin/End)
    /// so the snapshot is written to xterm as a single batch and the fit-
    /// ladder / `ResizeObserver` / peer-follow cannot interrupt mid-write.
    /// Cols/rows carry the dimensions the snapshot was encoded at - client
    /// compares to its current wrapper size and re-requests on mismatch.
    ReplayBegin {
        cols: u16,
        rows: u16,
    },
    ReplayEnd,
    SessionExit,
    /// SSH keyboard-interactive 认证提示
    SshAuthPrompt {
        pane_id: String,
        prompts: Vec<crate::session::SshAuthPrompt>,
    },
}

#[derive(Deserialize)]
pub struct InputRequest {
    pub pane_id: Option<String>,
    pub data: String,
}
